### ISSUE TITLE
Simulación de presión y fugas para los sectores

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#114]
Hay que simular la presión a través de una fórmula con respecto al caudal.

Para las fugas vamos a mirar una tabla que por cada sector nos indique el porcentaje de caudal y presión que debemos incrementar.

Simulamos una tabla para las fugas con estos campos:
sector | q | p | timeinstant
1          | 20% | -20% |  2018-01-01T17:00Z 
Esa tabla se rellena mediante el simulador. Si queremos simular una fuga debemos de subir q y bajar p.

@isapozuelo: Tienes que hacer una simulación de fugas tres sectores. Uno entra en fuga [rellenar]
@josemazo: Poner el conector para tener esa simulación en una tabla. Por otro lado tienes que hacer que el cálculo del consumo del sector sea como sigue:

Qt = SUM(Qi) + R% + Qf%
Pt = P(q) + Pf%

**Comment by josemazo** [comment]
A la espera de las nuevas simulaciones para completar las funciones.

**Comment by josemazo** [comment]
PR https://github.com/GeographicaGS/AquaGIS/pull/149

**Comment by josemazo** [comment]
https://github.com/GeographicaGS/AquaGIS/issues/21#issuecomment-357521348

**Comment by IgnacioDomingo** [comment]
@isapozuelo la simulación está hecha?

**Comment by IgnacioDomingo** [comment]
Revisar con lo hablado en la reunión para que funcione de acuerdo a la descripción inicial

**Comment by josemazo** [comment]
PR https://github.com/GeographicaGS/AquaGIS/pull/156

**Comment by alasarr** [comment]
Hay que hacer tres sectores (ahora hay dos):
1. Con anomalía los jueves
2. Fugas los lunes.
3. Sin nada.

**Comment by IgnacioDomingo** [comment]
El añadir nuevos sectores está en #145. Y entiendo que todos los sectores que se añadan que no tengan anomalía ni fuga, no necesitan entrada en la tabla. ¿Es así, @josemazo @isapozuelo ?

**Comment by josemazo** [comment]
¿En la tabla de fugas? Si, se guarda todo lo que viene del conector, con cuadal % y presion % a 0.

**Comment by IgnacioDomingo** [comment]
Ya me ha explicado @josemazo cómo funciona, es en el fichero JSON donde se indica cuándo se produce una fuga/anomalía. Los nuevos sectores por defecto vendrán sin fuga, así que no hay nada más que hacer.
