### ISSUE TITLE
Motor detección de fugas

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#115]
Lanzamos una tarea en el processing que llame a una función plpgsql, aplique las reglas de fuga para cada sector y actualice la tabla de resultados de fugas.

### Reglas de fuga

En una tabla tenemos la configuración de reglas de las fugas "leak_rules" . Algo como:

q        |      p    |     time | status
20      |    null  | 3600    |   1
40      |    -40  | 7200    |   2

status=1: Anomalía de consumo
status=2: Peligro de fuga

La tabla de last_data de los sectores debe tener una columna que sea "leak_status" y que tenga actualizado el último estado. Si es ok el valor debe ser 0.

### Tabla de resultados
Tenemos una tabla con el histórico de leaks por sectores. "leak_sector_historic". Esta tabla se actualiza cuando una fuga cambia de estado.

sector_id  | TimeInstant | status | rule

Esta tabla guarda los cambios de estado de los sectores. Cuando hay un cambio de estado se crea un nuevo registro para el nuevo estado.

Ejemplo:
1. Se detecta una anomalía de consumo. Se añade este registro: 
"1;2017-01-01T00:00Z;1;'Se detecta un consumo superior al 20%'"

2. Se detecta a la hora siguiente que la anomalía se ha corregido. 

Se actualiza el registro anterior
"1;2017-01-01T00:00Z;1;'Se detecta un consumo superior al 20%'"

Se añade un nuevo registro
"1;2017-01-01T01:00Z;0;null"

Hay que generar una variable Urbo para el campo status de esta tabla.

La generación de tablas hay que meterlas en las funciones de creación del vertical

**Comment by IgnacioDomingo** [comment]
Para que se pueda ofrecer como servicio avanzado, es necesario definirlo como un microservicio que sea el que hace los cálculos, recibiendo la información y aplicando las reglas.

**Comment by alasarr** [comment]
@padawannn @josemazo te explica cual es la tabla
