### ISSUE TITLE
Datos de consumo de edificios

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#117]
Hay una capa en el mapa que muestra el consumo por cada edificio. Una coropleta en base al consumo de la misma forma que el sector. Por tanto necesitamos el valor de todo el consumo del edificio (suma de todas las viviendas). Podemos hacer:

1. Añadir un campo para esto en la tabla de edificio.
2. Hacer un servicio que devuelva el geoJSON haciendo el cálculo al vuelo.

**Comment by IgnacioDomingo** [comment]
Introducir en metadatos de Urbo edificios (viviendas, etc) y su consumo, no dejar los edificios como estáticos

**Comment by josemazo** [comment]
A la espera de las nuevas simulaciones para completar las funciones.

**Comment by josemazo** [comment]
PR https://github.com/GeographicaGS/AquaGIS/pull/149

**Comment by josemazo** [comment]
https://github.com/GeographicaGS/AquaGIS/issues/21#issuecomment-357521348
