### ISSUE TITLE
Crear servicio para Widget: Previsión de consumo próxima semana

### ISSUE THREAD

**Issue by IgnacioDomingo** [GeographicaGS/AquaGIS#119]
Crear un servicio genérico para el widget

![Captura de pantalla 2017-12-22 a las 9.39.26.png](https://images.zenhubusercontent.com/57b2c068e40e5714b16d6586/d6b00c37-73c1-4c6f-9136-0c5684c9dda1)

**Comment by josemazo** [comment]
Me pongo con esto mientras obtengo la simulación _final_.

**Comment by josemazo** [comment]
Cuando lo suba a producción la llamada debería ser: POST /aljarafe/variables/timeserie

```
{
  "agg": ["SUM"],
  "vars": ["aq_cons.const.forecast"],
  "time": {
    "start": "2018-01-01T00:00:00Z",
    "finish": "2018-01-08T00:00:00Z",
    "step": "1d"
  },
  "filters": {
    "condition": {},
    "group": "aq_cons.sector.usage"
  }
}
```

**Comment by josemazo** [comment]
PR https://github.com/GeographicaGS/UrboCore-api/pull/18

**Comment by IgnacioDomingo** [comment]
Probado con sectores, funciona correctamente
