### ISSUE TITLE
Crear entorno de servidor

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#12]
Hay que montar el nuevo servidor en AWS para esto.

- [x] Montar Docker.

- [x] Configurar monitorización y backups.

- [x] PostgreSQL 10.

- [x] Mover context broker de nina aquí. Nada de autenticación en este context broker, a pelo.

**Comment by IgnacioDomingo** [comment]
las claves para acceder al servidor están en 1password, en la bóveda sistemas. El nombre es Jones
