### ISSUE TITLE
Crear servicio para Widget: previsión consumo según usos del suelo

### ISSUE THREAD

**Issue by IgnacioDomingo** [GeographicaGS/AquaGIS#120]
Crear servicio genérico para el widget
![Captura de pantalla 2017-12-22 a las 9.55.59.png](https://images.zenhubusercontent.com/57b2c068e40e5714b16d6586/80d8973f-8b28-459a-96a8-89630125fe4e)

**Comment by josemazo** [comment]
Cuando lo suba a producción la llamada debería ser: `POST /aljarafe/variables/timeserie`

```
{
  "agg": ["SUM"],
  "vars": ["aq_cons.const.forecast"],
  "time": {
    "start": "2018-01-01T00:00:00Z",
    "finish": "2018-01-08T00:00:00Z",
    "step": "1d"
  },
  "filters": {
    "condition": {},
    "group": "aq_cons.const.usage"
  }
}
```

**Comment by josemazo** [comment]
PR https://github.com/GeographicaGS/UrboCore-api/pull/18

**Comment by IgnacioDomingo** [comment]
probada con sectores, funciona correctamente
