### ISSUE TITLE
Diseño sección escenarios futuros

### ISSUE THREAD

**Issue by IgnacioDomingo** [GeographicaGS/AquaGIS#122]
- [ ] Diseño tarificación. Nuevo panel que muestre el basemap y permita hacer click en cada edificio. Esto hará que el front llame al servicio de tarificación de ISOIN y muestre en el tooltip los datos de la tarifa de agua aplicadas (ver detalles de datos a mostrar en http://iatdev.isoin.es/aquasig-web/docs)

- [ ] Diseño consumo futuro de agua. Diseñar nuevo panel que tenga las siguientes partes:
- Mapa con basemap, se utilizará para seleccionar la zona mediante bounding box.
- Widget que muestre el número de elementos por cada tipo (100 casa de tipo 1, 200 de tipo 2, 10 piscinas, etc.) que se ven en el mapa (con el filtro de bounding box), que haga una llamada al servicio web de ISOIN y muestre el consumo de un día y una gráfica con el consumo por cada hora. Será necesario tooltip o algo para poder indicar qué significa cada tipo
- El widget anterior, al pulsar sobre un botón de "+" (o añadir), creará una versión de sí mismo en la que se permitirá modificar cada uno de los conteos de tipos de casa (los valores se copiarán del widget original). Contendrá también un botón de "Aplicar" que se conectará con el servicio, y permitirá pintar el consumo de un día y la gráfica de consumo por hora. Tendrá también un botón de eliminar para quitar el widget.
- Puede haber más de una copia del widget, cada uno con sus propios datos.

**Comment by javigil-geo** [comment]
Actualizado:
https://projects.invisionapp.com/d/main#/console/12071697/274192051/preview

**Comment by IgnacioDomingo** [comment]
https://projects.invisionapp.com/d/main#/console/12071697/274192051/preview 
![image](https://user-images.githubusercontent.com/13120924/35106176-d6b67932-fc6d-11e7-9d67-f2c17c2734b2.png)

Por lo demás la veo muy bien, de todas formas, la de estado general la hablamos mañana, la veo un poco rara (no hay mucha más info que pintar, no sé si es mejor no ponerla directamente)

**Comment by IgnacioDomingo** [comment]
@alasarr revisa cuando puedas lo nuevo de escenarios futuros, yo lo veo todo bien, aunque el panel de estado general me sobra un poco
