### ISSUE TITLE
Integrar trabajo UPO del sistema de ahorro energético

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#125]
Revisar el trabajo realizado e integrarlo a la hora de obtener información de ahorro energético
- El entregable con el código es: https://drive.google.com/open?id=1-g4IiCdxLouoqGqbYVXEYuytuE1F1SOJ
- La documentación de la UPO es: https://drive.google.com/file/d/0B_upNBQysllibzRWQldCMXJma0lQZTFOaXpZU0IzYTlTUElV/view?usp=sharing
- Y en caso de que sea necesario, el enunciado con lo que se pedía es: https://drive.google.com/open?id=1s7yWA3-EQgfY_hvIuB8Yceel945-XSPNtCbOacEkYDQ

El objetivo es almacenar o tener acceso en Urbo a la planificación prevista para cada depósito para 1 día y la planificación de emergencia en caso de que haya una variación en el consumo. Pasos para ello:
* Hay que poner a disposición de sistema de ahorro la información que necesite de consumo previsto de sectores y las características del depósito. Esto puede implicar que lo que hay que hacer es meter las tablas extras del sistema de ahorro en el schema de Urbo y hacer que el sistema de ahorro use el schema de Urbo directamente
* Integrar sistema para que se hagan llamadas cada hora.
   * La llamada a las 00:00 será para hacer la planificación prevista (revisar si permite hacerlo a las 23:50 del día anterior, si no se les pide que lo permita).
   * Cada hora se llama para que compruebe si hay variaciones de consumo respecto a lo previsto, y en caso de que lo haya debe generar un plan de emergencia (que será el plan real que se siga).
* Hay que almacenar o poner a disposición de Urbo tanto el plan previsto para cada día como el plan real que se está siguiendo. Esto significa ir almacenando el plan previsto y el real para cada depósito.
* Hay que ir modificando la cantidad de agua que hay en cada depósito, llenándolo respecto al plan y disminuyendo su capacidad según el consumo del sector.

**Comment by alejandrohall** [comment]
He añadido los cambios a realizar por la UPO en https://docs.google.com/document/d/1LNr2Io0YkzUt6eXDB8zkh1jHVsEuKtYuUeDQRx_VgXE/edit

**Comment by alejandrohall** [comment]
Para integrar el trabajo de la UPO en el modelo existente hacen falta los siguientes cambios:

* La tabla forecast es sustituida por aq_cons_sector_agg_hour
* La tabla consumption es sustituida por aq_cons_sector_agg_hour
* La tabla tank_sector es sustituida por el parámetro reftank de aq_cons_sector
* La tabla tank es sustituida por la tabla aq_cons_sector pero añadiendo pump_flow: float (caudal en m3/h que la bomba es capaz de dar) y pump_power: float (potencia en MW que la bomba necesita).
* La tabla energy_price, tank_pump, tank_pump_no_opt y tank_pump_emergency tienen que ser creadas
* La tabla tank_start_level es sustituida por aq_cons_tank_measurand

**Comment by ignaciodomingo** [comment]
- [ ] Para integrar el trabajo de la UPO en el modelo existente hacen falta los siguientes cambios:

* La tabla forecast es sustituida por aq_cons_sector_agg_hour
* La tabla consumption es sustituida por aq_cons_sector_agg_hour
* La tabla tank_sector es sustituida por el parámetro reftank de aq_cons_sector
* La tabla tank es sustituida por la tabla aq_cons_tank pero añadiendo pump_flow: float (caudal en m3/h que la bomba es capaz de dar) y pump_power: float (potencia en MW que la bomba necesita).
* La tabla energy_price, tank_pump, tank_pump_no_opt y tank_pump_emergency tienen que ser creadas
* La tabla tank_start_level es sustituida por aq_cons_tank_measurand

- [ ] También el motor de optimización tiene que ser modificado para que las tablas que modifique sean las del vertical el el que se está usando

- [ ] Hay que modificar el endpoint /:scope/aq_cons/tank/:tank_id/plans para que devuelva los datos del schema real

**Comment by dandelea** [comment]
Parece que #280 está dificultando esta revisión.

**Comment by dandelea** [comment]
Adjunto el entregable tras la integración de los campos. 
He comprobado que funciona desde mi máquina conectándolo a un ámbito de pruebas. Paso la tarea a QA.
[Uploading... AquaSIG_fase2_v2.zip ]

**Comment by ignaciodomingo** [comment]
Esto hay que dejarlo corriendo en jones, @dandelea

**Comment by dandelea** [comment]
Con ánimo de registrar todo el proceso de despliegue:
- He ejecutado un script con la actualización del modelo del vertical _aq_cons_ en aljarafe:
```
-- TANK PUMP NO OPT
  CREATE TABLE IF NOT EXISTS aljarafe.aq_plan_tank_pump_no_opt (
    id_entity character varying(64) NOT NULL,
    "TimeInstant" timestamp without time zone,
    activated boolean NOT NULL,
    created_at timestamp without time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp without time zone DEFAULT timezone('utc'::text, now())
  );

  -- TANK PUMP OPT
  CREATE TABLE IF NOT EXISTS aljarafe.aq_plan_tank_pump_opt (
    id_entity character varying(64) NOT NULL,
    "TimeInstant" timestamp without time zone,
    activated boolean NOT NULL,
    created_at timestamp without time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp without time zone DEFAULT timezone('utc'::text, now())
  );

  -- TANK PUMP EMERGENCY
  CREATE TABLE IF NOT EXISTS aljarafe.aq_plan_tank_pump_emergency (
    id_entity character varying(64) NOT NULL,
    "TimeInstant" timestamp without time zone,
    activated boolean NOT NULL,
    created_at timestamp without time zone DEFAULT timezone('utc'::text, now()),
    updated_at timestamp without time zone DEFAULT timezone('utc'::text, now())
  );

SELECT urbo_tbowner_qry(ARRAY['aljarafe.aq_plan_tank_pump_no_opt', 'aljarafe.aq_plan_tank_pump_opt', 'aljarafe.aq_plan_tank_pump_emergency', 'aljarafe.aq_aux_energy_prices']);

--INSERCION DE PRECIOS DE ENERGIA (OMITIDO)
--INSERCION DE PRECIOS DE ENERGIA--

CREATE INDEX IF NOT EXISTS aljarafe_aq_plan_tank_pump_opt_ent_idx ON aljarafe.aq_plan_tank_pump_opt USING btree (id_entity);
CREATE INDEX IF NOT EXISTS aljarafe_aq_plan_tank_pump_no_opt_ent_idx ON aljarafe.aq_plan_tank_pump_no_opt USING btree (id_entity);
CREATE INDEX IF NOT EXISTS aljarafe_aq_plan_tank_pump_emergency_ent_idx ON aljarafe.aq_plan_tank_pump_emergency USING btree (id_entity);

ALTER TABLE aljarafe.aq_cons_sector ADD COLUMN reftank character varying(64);
ALTER TABLE aljarafe.aq_cons_sector_lastdata ADD COLUMN reftank character varying(64);
ALTER TABLE aljarafe.aq_cons_tank ADD COLUMN pump_flow double precision;
ALTER TABLE aljarafe.aq_cons_tank ADD COLUMN pump_power double precision;

-- VALORES DEL ESQUEMA 'PHASE2_V1'
INSERT INTO aljarafe.aq_cons_tank (id_entity,"TimeInstant",POSITION,capacity, min_level, max_level, pump_flow, pump_power)
VALUES ('tank:1',
        now(),
        ST_SetSRID(ST_MakePoint(-6.044797897338866, 37.354807847263324), 4326),
        5000,
        20,
        95,
        3600,
        0.4);

UPDATE aljarafe.aq_cons_sector SET reftank='tank:1';
UPDATE aljarafe.aq_cons_sector_lastdata SET reftank='tank:1';

ALTER TABLE aljarafe.aq_cons_sector ALTER COLUMN reftank SET NOT NULL;
ALTER TABLE aljarafe.aq_cons_sector_lastdata ALTER COLUMN reftank SET NOT NULL;
```

- He cambiado las referencias a tablas en todo el proyecto de la UPO.
- He desplegado el contenedor con nombre _upo_tank_planification_ dentro de _jones_.
- No he subido el proyecto a git. La última versión puede encontrarse en _/data/app/urbo/upo-energy-saving/_ de _jones_.

**Comment by ignaciodomingo** [comment]
@alejandrohall la semana que viene hay que revisar esto y los problemas de variables de tank. El endpoint tampoco parece funcionar bien

**Comment by alejandrohall** [comment]
Ya están solucionado los endpoints de tank, he dado de alta los permisos en el grafo de permisos, y adaptado algunas cosas del código.
