### ISSUE TITLE
Modelo de datos

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#13]
Crear la base de datos y el modelo de datos de la aplicación.

Esta tarea no incluye la carga de datos.

**Comment by josemazo** [comment]
Estamos modelando la parte puramente GIS de estos datos. Después tendremos que repasar los datos a simular para modelarlos también.

**Comment by isapozuelo** [comment]
Están creadas las tablas de datos estáticos iniciales. Una vez que carguemos datos habrá que retocar:
Esquema: infraestructura
- abastecimiento_line
- abastecimiento_point
- acometidas_line
- acometidas_point
- construccion
- deposito
- hidrante_line
- hidrante_point
- pozo_line
- pozo_point
- sector
- sensor
- valvula_line
- valvula_point
