### ISSUE TITLE
No sale logo en Login, cambiar favicon y título del header

### ISSUE THREAD

**Issue by IgnacioDomingo** [GeographicaGS/AquaGIS#136]
- [x] Arreglar logo en Login, no sale nada
- [x] Cambiar favicon por uno de Aquagis (@javigil-geo)
- [ ] Cambiar title del header a "Aquagis"

**Comment by javigil-geo** [comment]
Carpeta de favicon:
https://drive.google.com/open?id=1wLMbmYaz-CfgGK8Af4_XQw-iGzNDzwCp

**Comment by Josmorsot** [comment]
@neokore no encuentro la manera de cambiar el favicon y el title. Lo único que se me corre es hacerlo con javascript pero imagino que tendreis otra manera de hacerlo

**Comment by neokore** [comment]
No existe ningún método a día de hoy AFAIK. Así que yo optaría por JS de la forma más elegante posible, ya que el index no es themable (yet).
