### ISSUE TITLE
Informe hito 2

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#137]
https://drive.google.com/open?id=1ACsy8EERzI7wxlJ-4em-KVHe8LDZTiLf
- [x] Rellenar documentos
- [x] Añadir foto placa - https://drive.google.com/file/d/1ACsy8EERzI7wxlJ-4em-KVHe8LDZTiLf/view?usp=sharing

Carpeta: https://drive.google.com/drive/folders/1KT54mdJrexsf203EemfYPedGR1qRLz6w?usp=sharing

**Comment by isapozuelo** [comment]
@ignaciodomingo ya está listo para la última revisión antes de enviarlo a ISOIN.

AQUASIG_Informe Hito 2_v1.1

**Comment by ignaciodomingo** [comment]
@isapozuelo Está muy bien, sólo hay 3 cosas que veo:
- T3.3. Mantenimiento: Hay que decir que esto se encuentra en desarrollo y que todavía no está terminado, por la descripción de las tareas parece que ya está terminado
- T3.4. Panel: Los verticales son ahora 3: Consumo de agua (agrupa patrones de consumo, fuga y ahorro energético), Mantenimiento y Escenarios futuros
- Deja un comentario puesto en las conclusiones en la parte de las cosas de la actividad de cliente, indicando a ISOIN que ponga ahí lo que vean mejor

**Comment by isapozuelo** [comment]
¡Gracias por los comentarios @ignaciodomingo ! lo cambio y te aviso.
