### ISSUE TITLE
Documentación administrativa hito 2

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#138]
- [x] Excel Datos Económicos
Parece haber algo ya en https://drive.google.com/open?id=1CPmbI3B9LY-iWFa0-9pn7I5M2xtKytFR
Hay que copiarlo, revisar que está completo y que incluye los costes añadidos de adevice.

- Documentación soporte (basada en el excel)
Ya hay algo en: https://drive.google.com/open?id=0B1IMLPpBpLH1eEVqVS1hN2xRa1U
Documentos a dar:
Personal:
- [x] a. TC2 de las personas justificadas
- [x] b. Modelo 190 o Certificado de Retenciones del IRPF del año 2016. Nóminas para el
mes de enero de 2017 (revisar fechas, no parecen correctas)
- [x] c. Convenio Colectivo
- [x] d. Soporte de control de horas mensual para cada persona, firmado y sellado
2. Colaboraciones Externas:
- [x] a. Factura
- [ ] b. Justificante de pago
3. Materiales:
- [x] a. Factura
- [x] b. Justificante de pago

- Otra documentación
- [x] Certificado de estar al corriente de pagos de las obligaciones tributarias (estatales y
autonómicas)
- [x] Certificado de estar al corriente de pagos de la Seguridad Social
- [x] Declaraciones responsables Ley General de Subvenciones (art.31.3 y art.29.7)

Poner los documentos en una nueva carpeta en https://drive.google.com/open?id=1KT54mdJrexsf203EemfYPedGR1qRLz6w 

Guía de justificación: https://drive.google.com/open?id=1TWPogQ0fRsTyHOOUjNOeOi0aWj3ZdTmC

**Comment by ignaciodomingo** [comment]
Esta tarea ya se puede empezar, nos han confirmado la aprobación del cambio de presupuesto por parte del CDTI para 2017

**Comment by ignaciodomingo** [comment]
Había dos carpetas para las auditorías y justificaciones para cada hito. Lo he juntado todo. Ahora la carpeta maestra es https://drive.google.com/open?id=1KT54mdJrexsf203EemfYPedGR1qRLz6w

**Comment by ignaciodomingo** [comment]
limpiado excel de comentarios y enviado a isoin para su revisión

**Comment by jorgechg** [comment]
Documentación subida. Observaciones:

2. Colaboraciones Externas_: Faltan los justificantes de pago. Se realizarán los últimos dos a la UPO a final de mes. Se suben todos cuando se realice.

3. Materiales: No tenemos gastos asociados esta anualidad.
