### ISSUE TITLE
Carga de datos estáticos

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#14]
Cargar los datos estáticos de Aljarafesa definidos en #13

**Comment by alasarr** [comment]
No incluimos en esta tarea la carga de datos de usos de viviendas.

**Comment by isapozuelo** [comment]
He cogido como muestra el municipio de Mairena del Aljarafe. Están los siguientes datos:
Esquema: infraestructura
- abastecimiento_line
- abastecimiento_point
- acometidas_line
- acometidas_point
- deposito (EIEL de Sevilla)
- hidrante_line
- hidrante_point
- pozo_line
- pozo_point
- sector
- sensor
- valvula_line
- valvula_point

Falta coger los datos de las 10 viviendas. Ya tengo los datos de catastro de dónde los vamos a coger, falta hacer la selección y cargarlos en la tabla infraestructura.construccion

**Comment by isapozuelo** [comment]
Ya están todos.

**Comment by IgnacioDomingo** [comment]
Todo perfecto, pero revisando hemos visto que las parcelas no están asociadas a sectores, please @isapozuelo asocialas.

**Comment by isapozuelo** [comment]
@IgnacioDomingo ¡hecho!

**Comment by IgnacioDomingo** [comment]
Gracias!
