### ISSUE TITLE
E3.1. Procesado e integración de los datos en tiempo real

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#140]
Incluirlo en https://drive.google.com/drive/u/0/folders/13-4DhI3YMLs0VuytvQN-aJdOl-GeAK-u

Para el entregable:
- ISOIN describe proceso hasta context broker
- Nosotros describimos funcionamiento conector y cómo se introducen los datos (incluyendo agregación en sectores, normalización, ejecución de servicios que se vean afectados, etc)

**Comment by isapozuelo** [comment]
Están en esta versión del documento.
AQUASIG_A1_E1.3_Modelado de la informacion y arquitectura del sistema basada en SIGGO_v1.4
