### ISSUE TITLE
E3.2. Servicios avanzados dirigidos a distribuidoras de abastecimiento urbano de agua

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#141]
https://drive.google.com/open?id=1OQC3KBU-tE3EAMgAVasciuTkSdeh6Gxm
Hay que únicamente documentar los servicios. No hace falta explicar su funcionamiento interno al 100%, sino más bien a alto nivel cómo sería su uso e incluir algunos pantallazos/mockups. No hay que meter código en el entregable.

- [ ] T3.2.1 Detección y caracterización de patrones de consumo urbano de agua (tenemos que hacerlo nosotros o ponérselo a la UPO)
- T3.2.2 Sistema DSS de gestión avanzada del consumo urbano. Tiene dos partes:
- [x] Detección de fugas (lo hacemos nosotros, tarea de doc es #124 )
- [x] Ahorro energético (lo hace la UPO)

- [ ] T3.2.3 Generador inteligente de escenarios futuros de consumo urbano de agua (ISOIN)
- [ ] T3.2.4 Simulador avanzado de tarificación del consumo urbano de agua (ISOIN)

**Comment by ignaciodomingo** [comment]
Lo que tenemos que hacer primero es crear el documento con el índice, nos basamos en cualquier otro de Aquagis que hayamos trabajado y ponemos los puntos que aparecen arriba. Con eso salvamos la semana

**Comment by isapozuelo** [comment]
@ignaciodomingo aquí está el documento:
https://drive.google.com/open?id=1Xojmnzn4EvXrKwy7hF--5Vx2tFqg6SeI

**Comment by isapozuelo** [comment]
Aquí está el documento con nuestras secciones completas:
[AQUASIG_A3_E3.2._ServiciosAvanzadosDirigidosADistribuidoras_v3.0.docx](https://github.com/GeographicaGS/AquaGIS/files/1731465/AQUASIG_A3_E3.2._ServiciosAvanzadosDirigidosADistribuidoras_v3.0.docx)
