### ISSUE TITLE
Mejoras simulación

### ISSUE THREAD

**Issue by IgnacioDomingo** [GeographicaGS/AquaGIS#145]
- [ ] Definir sectores por cantidad de población. ( empezar ampliando los sectores existentes para que ocupen más espacio)
- [ ] Simular más construcciones dentro de cada sector

**Comment by alasarr** [comment]
Importante ver con @cayetanobv , no podemos crecer y tener un mega json que tenga una entidad por cada construcción.

**Comment by IgnacioDomingo** [comment]
Cierro esta tarea ya que la hemos transformado en #182
