### ISSUE TITLE
El endpoint variables/timeserie con group no es compatible con los formatos que espera el frontend

### ISSUE THREAD

**Issue by neokore** [GeographicaGS/AquaGIS#147]
El endpoint `/variables/timeserie` devuelve los datos en un formato que no se corresponde al esperado en el frontend cuando se le pide agrupar por una variable. Este endpoint ya existía en la API de Urbo, pero era usada sólo en watering con un comportamiento distinto (sin group) donde sí coinciden.

El formato esperado por el frontend sería algo así:
```
[
  {
     "time": "2017-04-07T22:00:00.000Z",
     "data": {
        "wt_soilhumidity": 1234,
        "wt_temperature": 2345,
        "wt_pressure": 3456,
        "wt_solaradiat": 4567,
        "seconds": 5678
      }
  },
  ...
]
```

Sin embargo si para AquaGIS pedimos los datos agrupados nos devuelve un formato como este:
```
[
  {
     "time": "2017-04-07T22:00:00.000Z",
     "data": {
        "aq_cons.sector.forecast": 1234,
        "aq_cons.sector.usage":"domestic"
      }
  },
  {
     "time": "2017-04-07T22:00:00.000Z",
     "data": {
        "aq_cons.sector.forecast": 2345,
        "aq_cons.sector.usage":"industrial"
      }
  },
  ...
]
```
Lo que causa dos cambios respecto a la salida anterior: agrega varias entradas para el mismo elemento de fecha y hace que sea necesario agrupar manualmente los datos para poder obtener la información importante con el mismo formato que antes que sería algo así:
```
[
  {
     "time": "2017-04-07T22:00:00.000Z",
     "data": {
        "domestic": 1234,
        "industrial": 2345
      }
  },
  ...
]
```
Por lo que estimo (opinión personal) que en realidad el servicio tras decirle que agrupe, no agrupa, si no que está funcionando como si al servicio original le pidieras varias variables sin agrupar. Aunque realmente en el backend sigue haciendo lo que antes, pasar el nombre de la variable en lugar del valor, pero cuando se pide una agrupación lo que interesa es saber los valores de la agrupación, y no tanto el nombre de la variable usada para agrupar.

Esto supone en frontend tener que colecciones nuevas que parseen los datos de forma que se puedan leer correctamente en los widgets actuales; y si se arregla en el backend, tener que aplicar también cambios (@josemazo puede arrojar luz por su parte). Con el problema de falta de tiempo que hay en ambos lados.

**Comment by josemazo** [comment]
Has tardao más en escribir esto que en hacer el formateador...

Cierto, el servicio no agrupaba, simplemente lo deje como si se pidiesen dos variables distintas. Aunque es culpa mía, fue lo que me salió en el estado del servicio tal cual lo dejó su creador.

Ahora agrupa como si originalmente se le piden dos agregados de la misma variable.

```json
[
    {
        "time": "2018-01-01T00:00:00.000Z",
        "data": {
            "aq_cons.sector.consumption": [
                {
                    "agg": "domestic",
                    "value": 16932024.3956305
                },
                {
                    "agg": "industrial",
                    "value": 75888205.5756315
                }
            ]
        }
    },
    {
        "time": "2018-01-02T00:00:00.000Z",
        "data": {
            "aq_cons.sector.consumption": [
                {
                    "agg": "domestic",
                    "value": 16657271.5304962
                },
                {
                    "agg": "industrial",
                    "value": 74649574.3525637
                }
            ]
        }
    }
]
```

**Comment by neokore** [comment]
En realidad no he tardado practicamente nada en meter esos datos, recuerda que tienes las tres tildes de markdown y puedes copiar y pegar de la salida de Chrome/Firefox/Postman 😉.

Anyway, el problema no es escribir el formateador simplemente, sino volver a la dinámica de clases personalizadas para la misma tarea en cada vertical, que fuerza a reescribir mucho código y lo hace menos mantenible.

Por otra parte, revisemos luego el formato que propones si es posible, el problema de formateo se tendrá que solucionar hablando entre back y front y definiendo un formato determinado, si se realiza un cambio por un lado que fuerce a la otra parte a seguir adaptando código no habremos avanzado nada. En este caso no sé si esa salida la tenemos ya contemplada o no en cualquiera de las colecciones, ni si en caso de que no se haya utilizado antes, si realmente precisamos de un formato nuevo de salida.

**Comment by josemazo** [comment]
Esto se está llendo de madre. Ese es el formato que hizo javi Muñoz para
este servicio cuando se agregan las variables.

**Comment by neokore** [comment]
Ains... no he dicho nada acerca de que ese formato sea o deje de ser correcto, sólo que antes de actuar es mejor revisar entre ambas partes la salida que debemos: 
> En este caso no sé si esa salida la tenemos ya contemplada o no en cualquiera de las colecciones [...]

Si ese es un formato ya usado en Urbo, genial, no habría más cambios que aplicar, sólo digo que no lo he comprobado; pero de verdad, para temas que afecten al desarrollo tanto de frontend como de backend, veámoslo con Ignacio antes de tomar ninguna decisión.

**Comment by josemazo** [comment]
Pero si he comentado ya dos veces que así funciona ese servicio cuando se
le piden agregados.

**Comment by IgnacioDomingo** [comment]
Nos sentamos ahora y lo vemos

**Comment by alasarr** [comment]
Haya paz, si nos vamos a pegar que sea de verdad, no con github de por medio.

Fuera de coñas, el formato está definido en la reference, simplemente había un bug que ya se ha corregido (según veo en el último comentario de @josemazo ). Ya con eso debería rular

**Comment by IgnacioDomingo** [comment]
Incluir en colecciones de urbo core los cambios para el stacked
