### ISSUE TITLE
Entender simulador

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#15]
Organizar una charla en la que @cayetanobv os explique el simulador.

El objetivo 1 de esta charla es que isa haga una simulación muy básica: dos sensores que envíen una medida y vea que los datos lleguen a orion (nada de conectores y postgis)

Isa debe ser capaz de:

1. Generar un fichero de configuración.
2. Lanzar la simulación desde su equipo.
3. Verificar que los datos llegan al context broker.

El objetivo 2 es que entienda las diferentes funcionalidades del simulador. No lo tiene que controlar todo, pero si donde mirar para ir avanzando. Le tendrá que dar la tabarra a @cayetanobv cuando se ponga con las simulaciones complejas

**Comment by josemazo** [comment]
Cayetano ya se reunió el lunes 4 y nos explicó como funcionaba la configuración del simulador. Ya tendríamos que ponernos con la simulación de prueba.

**Comment by josemazo** [comment]
Todo listo. Las simulaciones se lanzan desde Jones: @isapozuelo sube la configuración del simulador con FileZilla, por Putty reinicia el simulador y con Postman comprueba Orion 💃
