### ISSUE TITLE
Previsión de presión 

### ISSUE THREAD

**Issue by IgnacioDomingo** [GeographicaGS/AquaGIS#150]
- [x] Añadir metadatos presión y forecast de presión por sector en Urbo
- [x] Añadir simulación de previsión de presión por sector

**Comment by josemazo** [comment]
PR https://github.com/GeographicaGS/AquaGIS/pull/156

**Comment by IgnacioDomingo** [comment]
@josemazo  No sé si los metadatos están bien, estoy intentando hacer la siguiente petición:
`POST /aljarafe/variables/aq_cons.sector.pressure_forecast/weekserie` 
```
{
 "agg": "SUM",
 "time": {
 "start": "2018-01-22T00:00:00Z",
   "finish": "2018-01-29T00:00:00Z"
 },
 "filters": {}
}
```

Y me está devolviendo
```
{
    "message": "Invalid row",
    "error": {}
}
```

Lo mismo para forescast, pressure funciona. ¿Puedes revisarlo?

**Comment by josemazo** [comment]
Arreglado, problema de metadata en el arbol de permisos, que hice el codigo sql que lo metía pero no lo ejecuté.

**Comment by alasarr** [comment]
Falta el agregado de presión

**Comment by IgnacioDomingo** [comment]
De pressure hay datos, pero pocos, imagino que por haber iniciado el simulador hace menos. También recordad que pressure no van a venir datos del futuro, sólo de días que hayan pasado. Poniendo esto salen datos:
`POST /aljarafe/variables/aq_cons.sector.pressure/weekserie`
```
{
  "agg": "SUM",
  "time": {
  "start": "2018-01-15T00:00:00Z",
    "finish": "2018-01-22T00:00:00Z"
  },
  "filters": {}
}
```

Hay datos desde el viernes por la tarde

**Comment by josemazo** [comment]
Sobre la confusión de esta mañana y de lo que hablamos ayer: Lo que faltaba era la previsión de presión, ya que no podíamos comparar con nada la presión actual para ver si había fuga. La tabla de agregados no necesita presión en sí (el consumo si se metió ya que había servicios que dependían directamente de él, y además que realmente es una entidad distinta a caudal).

Entonces, la presión _horaria_ que hace falta para compararla con la previsión de presión es una media de las presiones durante cierta hora. Si solo se va a usar en ese cálculo, puedo hablar con @padawannn si realmente la necesita separada o puede hacer esa media, y ya ver si implementarla o no.

Ya me dices @alasarr si implentarla si o si, o que decida @padawannn.

**Comment by josemazo** [comment]
@IgnacioDomingo sobre tu comentario https://github.com/GeographicaGS/AquaGIS/issues/150#issuecomment-358259783, todo correcto.

**Comment by josemazo** [comment]
Sobre https://github.com/GeographicaGS/AquaGIS/issues/150#issuecomment-358293335, @padawannn me ha pedio que lo meta.

**Comment by josemazo** [comment]
Sobre https://github.com/GeographicaGS/AquaGIS/issues/150#issuecomment-358293335, @padawannn me ha pedio que lo meta.
