### ISSUE TITLE
Definir fase 2 de ahorro energético de UPO

### ISSUE THREAD

**Issue by IgnacioDomingo** [GeographicaGS/AquaGIS#151]
Dar más detalle para la fase 2 del documento https://docs.google.com/document/d/1s7yWA3-EQgfY_hvIuB8Yceel945-XSPNtCbOacEkYDQ/edit?usp=sharing

Una vez listo, hay que enviarlo a la UPO

**Comment by josemazo** [comment]
Datos nuevos creados en el esquema `phase2_v1`. Adjunto el nuevo documento con la fase 2:
 [Ahorro energético.pdf](https://github.com/GeographicaGS/AquaGIS/files/1655123/Ahorro.energetico.pdf)

También está en el Drive: `Projects - WIP/AQUASIG/analisis/Ahorro energético`

@IgnacioDomingo si al leer el doc no entiendes algo, lo vemos y lo arreglo.
