### ISSUE TITLE
Actualización diseño

### ISSUE THREAD

**Issue by IgnacioDomingo** [GeographicaGS/AquaGIS#154]
NOTA: Cuando indico eliminar, ocultar también me vale. He ido colocando las pantallas en el orden en que aparecen.

9 - https://projects.invisionapp.com/d/main#/console/12071697/256620475/preview
Eliminar widget de temperatura, añadir mapa de tiempo real.

10 - https://projects.invisionapp.com/d/main#/console/12071697/256620479/preview
11 - https://projects.invisionapp.com/d/main#/console/12071697/271475979/preview
Eliminar widget de temperatura

12 - https://projects.invisionapp.com/d/main#/console/12071697/256620478/preview
Eliminar pantalla completa

13 - https://projects.invisionapp.com/d/main#/console/12071697/256620477/preview
Eliminar widget de temperatura

14 - https://projects.invisionapp.com/d/main#/console/12071697/256620476/preview
Eliminar pantalla completa

21 - https://projects.invisionapp.com/d/main#/console/12071697/257399000/preview
22 - https://projects.invisionapp.com/d/main#/console/12071697/258538011/preview
Eliminar mapa (la idea es que sea como una ficha)

23 al 28 - https://projects.invisionapp.com/d/main#/console/12071697/257792474/preview (y todas las móviles)
Eliminar "Alerta" del submenú (si es sencillo)

29 - https://projects.invisionapp.com/d/main#/console/12071697/257792473/preview
Eliminar pantalla completa

32 - https://projects.invisionapp.com/d/main#/console/12071697/254308988/preview
33 - https://projects.invisionapp.com/d/main#/console/12071697/254308428/preview
34 - https://projects.invisionapp.com/d/main#/console/12071697/254308989/preview
35 - https://projects.invisionapp.com/d/main#/console/12071697/254308987/preview
Eliminar pantalla completa

**Comment by javigil-geo** [comment]
Tenemos que revisar las últimas porque Invision ha cambiado el orden de las pantallas y no se corresponden.

**Comment by javigil-geo** [comment]
Actualizado.

**Comment by IgnacioDomingo** [comment]
Cambia el orden de https://projects.invisionapp.com/d/main#/console/12071697/272700251/preview y https://projects.invisionapp.com/d/main#/console/12071697/257792472/preview , que se han quedado un poco desordenadas.

Por lo demás perfe
