### ISSUE TITLE
Selector del basemap

### ISSUE THREAD

**Issue by IgnacioDomingo** [GeographicaGS/AquaGIS#155]
Realizar el selector del basemap

@javigil-geo necesitamos diseño

**Comment by javigil-geo** [comment]
https://projects.invisionapp.com/d/main#/console/12071697/256620479/preview

**Comment by IgnacioDomingo** [comment]
Cuando se desarrolle, tener en cuenta que al cambiar el tamaño del mapa, el selector debería moverse y no quedarse en medio

**Comment by IgnacioDomingo** [comment]
- [ ] El selector de basemap y el pie de la leyenda se quedan en medio de la pantalla al ampliar el mapa. Deberían moverse (esto estaba en el comentario anterior ya)
