### ISSUE TITLE
Añadir información para simulación a cada construcción

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#158]
Hay que añadir la siguiente información estática a cada construcción:
- [x] información para simulación consumo:
- Hay que asociar una tabla a cada construcción. En esa tabla, se muestran los distintos tipos de inmueble que aplican a cada construcción (por ejemplo, una construcción puede tener uso vivienda y uso servicios). La tabla tendrá los siguientes campos: id_construccion, tipología, tipo. Tipología será un valor de entre casa, edificio, industrial, terciario, hotel, deportiva, piscina (puede ser un enumerado). Tipo dependerá de cada tipología, ver detalles en http://iatdev.isoin.es/aquasig-web/docs 

- [x] Información para tarificación:
- calibre: Entero con el calibre del contador. Para doméstico (viviendas) el valor posible es: [15, 20, 25, 30, 40, 50, 65, 80, 100] y para no domésticos: [15, 20, 25, 30, 40, 50, 65, 80, 100, 125, 150, 200, 250, 300, 400, 500]. Cualquier otro valor es inválido.

- [x] Simular toda la nueva información para todas las construcciones

**Comment by isapozuelo** [comment]
calibre:
- crear tabla de calibres para cada construcción con valores random.

**Comment by isapozuelo** [comment]
@ignaciodomingo ya están. He aplicado todo a nivel de construcción. Las tablas son:
- aljarafe.aq_cata_const_type: tabla de catálogo con los diferentes tipos y tipologías.
- aljarafe.aq_cons_const_simulation: tabla con todas las construcciones y las columnas de simulación y tarificación: type_name, type_id, type_parameter, type_value, calibre

**Comment by isapozuelo** [comment]
@ignaciodomingo ya están aplicados los cambios que hemos hablado:

- Se han añadido construcciones de tipo 'Hospedaje' y 'Edificio' con sus correspondientes valores y calibres.
- Se ha generado una tabla aljarafe.aq_cons_plot_simulation con el plot_id, tipo (1 para doméstico y 0 para no doméstico) y el calibre en cada caso. Se ha hecho una selección random de la primera construcción de cada plot.
