### ISSUE TITLE
Simulación zona de 10 viviendas

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#16]
Vamos a coger una zona de 10 viviendas y vamos a simular los datos de consumo de las mismas.

Los datos estáticos de viviendas para esta zona lo hacemos en esta tarea

**Comment by isapozuelo** [comment]
Para la simulación hablé con Javier Blanco para consultarle los parámetros normales para detectar fugas y cuáles son los tipos de uso.
Aquí hay un resumen de la conversación:
https://docs.google.com/document/d/1vLJWeNP3ek0EzWkJB9i8k0WRg_5yIjmWj63iM_h3a4Q/edit

**Comment by isapozuelo** [comment]
[config_aquagis_ngsi.zip](https://github.com/GeographicaGS/AquaGIS/files/1579006/config_aquagis_ngsi.zip)
