### ISSUE TITLE
Parámetros geojson de sectores y viviendas

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#160]
![Captura de pantalla 2018-01-17 a las 10.46.43.png](https://images.zenhubusercontent.com/57b2c068e40e5714b16d6586/69b5f327-1c28-4626-ac4f-e6a4d0f40378)

El geojson de sectores y viviendas, se puede llamar con la selección de fecha y el flag de tiempo real o predicción

**Comment by IgnacioDomingo** [comment]
Lo que necesitamos es algo como `:scope/maps/:entity/now` pero que reciba también un filtro de tiempo y una función de agregación

**Comment by josemazo** [comment]
https://geographicags.github.io/Urbo-docs/reference/maps/#post-scopemapsentityhistoric

PR https://github.com/GeographicaGS/UrboCore-api/pull/19

**Comment by josemazo** [comment]
@alasarr viendo esto en mis notas, pensaba que los servicios de GeoJSON solo iban a dar el lastdata (o la tabla en sí si es una de catalogo estilo las acometidas) y que los agregados los íbamos a coger de otro servicio y metérselos al mapa. Pero bueno, ya está todo listo.
