### ISSUE TITLE
Crear vertical de simulación

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#169]
Crear vertical de simulación.

Este vertical no tendrá tablas propias, usará las de aq_cons.

Pantallas a partir de https://projects.invisionapp.com/d/main#/console/12071697/274192051/preview

**Comment by dandelea** [comment]
El vertical creo que lo podemos dar por completado.

**Comment by ignaciodomingo** [comment]
Cambiar nombre a "Escenarios futuros" para que esté de acuerdo con el diseño

**Comment by dandelea** [comment]
Cambiado.
