### ISSUE TITLE
Entorno Urbo

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#17]
1. Base de datos Urbo. Pilla la de walter y carga los esquemas de metadatos y la tabla de los conectores.

2. Despliega una versión de la API, Processing, Connector, Front. Jenkins y autodeploy. El repo es este.

3. Crear una primera versión del vertical, con los metadatos de los sensores de los sectores.

4. Árbol de permisos. Solo el user admin

**Comment by alasarr** [comment]
En el front no hay que crear el vertical nuevo, simplemente el login y la pantalla de ámbitos. Crea el ámbito "Aljarafe"

**Comment by josemazo** [comment]
API en https://urbo-aquagis-backend.geographica.gs/api/
Usuario y pass como en Urbo Production.

**Comment by josemazo** [comment]
Listo, con autodeploys (faltaría descomentar en jones los scripts de los conectores y el processing).
Faltaría el front.

**Comment by alasarr** [comment]
¿Dónde está el código de la API?

**Comment by alasarr** [comment]
Imagino que no lo has puesto aún porque no hay ningún vertical, pero necesito saber si le has puesto algún nombre a los verticales o lo pongo yo, para hacerlos coincidir.

**Comment by josemazo** [comment]
No, todavía no hay nada de código de aquagis. Si los pones primero avísame y los uso.

**Comment by alasarr** [comment]
Desplegada mi parte del front. http://aquagis.geographica.io

He subido el código a la branch master.

Cosas que quedan:

- [ ] Crear metadatos del vertical de patrones de consumo, se tiene que llamar aq_cons: @josemazo 

Cuando estén los metadatos deberíais pasar de la ventana del login y ver dos paneles vacío. Esto debería ser el final de esta tarea. Si hay problemas con el front me comentáis.

**Comment by josemazo** [comment]
Los paneles no salen porque creo que no hay servicios: http://aquagis.geographica.io/es/aljarafe/aq_cons/dashboard

Da un 404 horroroso.

**Comment by josemazo** [comment]
¿Como va esto @alasarr? Parece que has puesto al API de walter, no? Da los mismos problemas, parece que ese front no tiene desplegados los verticales.

**Comment by josemazo** [comment]
Metadatos buenos subidos (aunque no hay "diferencia" usable con los anteriores).

Cosas que pasan:

- Las entidades no se activan en el panel de admin. No se hace ninguna petición al activarlas.
- Al obtener los permisos del vertical, da un 500.
- Al entrar en Urbo, da un 404, ya que intenta acceder al único vertical del único ambito, y no hay front para `aq_cons`.

CC: @alasarr

**Comment by josemazo** [comment]
El árbol de permisos se creó, pero ninguna entidad tenía asignado el usuario admin. Puede ser que ese caso se hiciera a mano, y para el resto de usuarios **_irá bien_**.

**Comment by alasarr** [comment]
Ya funciona lo del 404 y lo de los permisos.
