### ISSUE TITLE
Cambios backend

### ISSUE THREAD

**Issue by IgnacioDomingo** [GeographicaGS/AquaGIS#176]
Devolver esta información en el GeoJSON
- [x] plot
- tipos de construcciones
- numero de construcciones
- consumo previsto

**Comment by josemazo** [comment]
Pongo aquí el comentario de @alasarr en Slack sobre esta issue:

> Chavales, vamos a crear la issue en github , pero para obtener el dato de los plots, para saber cuántas viviendas hay y cuantas construcciones, @jcamacho va a hacer un servicio independiente. Este servicio devolverá un array con todas las construcciones de la parcela
> 
> Esto lo tendréis que usar para poner en el popup de la parcela el número de viviendas y los tipos

Aquí está la doc: https://geographicags.github.io/Urbo-docs/reference/aq_cons/#get-scopeaq_consplotid_plotconstructions

Ya está en producción. Si se necesita algún cambio o no se entiende cualquiera cosa avisadme, incluso en el finde.

**Comment by IgnacioDomingo** [comment]
@josemazo veo bien el servicio rest para recibir las construcciones hijas
¿Cómo podemos conseguir el forecast calculado del plot? ¿Es mejor meterlo igual que aq_cons.plot.consumption?

**Comment by josemazo** [comment]
Añadido el redimiento en la previsión de los sectores.

@padawannn, cuando tengas que calcular el estado de la fuga no tendrás que tener en cuenta el rendimiento, porque ya lo tienen el consumo y su previsión aplicados.
