### ISSUE TITLE
Conector de datos de consumo de viviendas

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#18]
La simulación sacada de #16

**Comment by josemazo** [comment]
Conector configurado, a la espera de la simulación de estáticos.

**Comment by josemazo** [comment]
Que no se me olvide subir la config cuando la valide.

**Comment by josemazo** [comment]
PR https://github.com/GeographicaGS/AquaGIS/pull/149

**Comment by josemazo** [comment]
https://github.com/GeographicaGS/AquaGIS/issues/21#issuecomment-357521348
