### ISSUE TITLE
Documentación módulo ahorro energético

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#19]
Un documento para pasar al tipo de la UPO el lunes. Tiene que estar hiper claro lo que tienen que hacer, incluso definir las estructuras de datos

**Comment by IgnacioDomingo** [comment]
subido a google docs y ya compartido con la UPO en https://docs.google.com/document/d/1s7yWA3-EQgfY_hvIuB8Yceel945-XSPNtCbOacEkYDQ/edit#
