### ISSUE TITLE
Revisión diseño vertical patrones de consumo

### ISSUE THREAD

**Issue by IgnacioDomingo** [GeographicaGS/AquaGIS#200]

**Comment by javigil-geo** [comment]
- [ ] Cambiar estilos a popups.
He añadido documentación en esta pantalla:
https://projects.invisionapp.com/d/main#/console/12071697/256620479/preview
y tenéis una similar en esta:
https://projects.invisionapp.com/d/main#/console/12071697/273948180/preview

- [ ] Falta icono del vertical, como están colocados en Urbo.
![captura de pantalla 2018-01-24 a las 11 00 54](https://user-images.githubusercontent.com/19855697/35326107-e948401c-00f5-11e8-9593-0638035bee3d.png)
![captura de pantalla 2018-01-24 a las 10 27 47](https://user-images.githubusercontent.com/19855697/35326109-e963251c-00f5-11e8-855e-9b6aae4aa83f.png)

- [ ] Vamos a añadirle a la leyenda un texto de "menos - más" para que se entienda el rango de color.
![captura de pantalla 2018-01-24 a las 10 47 50](https://user-images.githubusercontent.com/19855697/35326163-1bafdfb0-00f6-11e8-9241-b9fcff919d13.png)
![captura de pantalla 2018-01-24 a las 11 02 09](https://user-images.githubusercontent.com/19855697/35326164-1bcb5506-00f6-11e8-8f2c-4e3cbe7d7090.png)

- [ ] En Estado General, cambiar el títlo del widget de "Tiempo real" a "Mapa" o "Sensores".
Podemos añadir también enlace a los widgets de "Previsión de consumo semanal" y "Previsión de consumo por usos de suelo" para que lleven al visor de "Previsión semanal".

- [ ] Aumentar el margen inferior del botón "Ampliar mapa", que sea igual al margen superior del botón del "bounding box".
![captura de pantalla 2018-01-24 a las 11 10 54](https://user-images.githubusercontent.com/19855697/35326570-64cfa2e2-00f7-11e8-9290-47fe2c24c469.png)

- [ ] Algunos colores en los widgets siguen siendo Urbo:
Elementos activos como el desplegable "1 DÍA" van en #64B6D9
El gris de las gráficas debe ser #98B2C9
![captura de pantalla 2018-01-24 a las 11 14 32](https://user-images.githubusercontent.com/19855697/35326740-dc2098ec-00f7-11e8-80b2-3c7c4a9329c2.png)
https://projects.invisionapp.com/d/main#/console/12071697/272446564/preview

- [ ] Falta la flecha para que se perciba mejor el dropdown
![captura de pantalla 2018-01-24 a las 11 28 21](https://user-images.githubusercontent.com/19855697/35327401-ce4b3e64-00f9-11e8-8f5b-7e652c7a6daf.png)

**Comment by javigil-geo** [comment]
![captura de pantalla 2018-01-24 a las 11 37 13](https://user-images.githubusercontent.com/19855697/35327844-f2c1d64e-00fa-11e8-83c9-35b09b390d91.png)
Veo los iconos de la leyenda un poco pixelados en los bordes, los he exportado de nuevo.

**Comment by IgnacioDomingo** [comment]
@Josmorsot revisa lo que comenta Javi, please

**Comment by IgnacioDomingo** [comment]
- [ ] Revisar también que el menú de admin queda por de bajo de la barra de cambiar de panel:
![image](https://user-images.githubusercontent.com/13120924/35330674-9ca7c3ea-0104-11e8-9d56-dcda8353c14d.png)

**Comment by IgnacioDomingo** [comment]
- [ ] Los popups nuevos no funcionan bien en los laterales, les falta el estilo
![image](https://user-images.githubusercontent.com/13120924/35395580-0ae4cb14-01eb-11e8-957e-92bf8d08169b.png)
- [ ] Se han vuelto a perder los iconos de la leyenda:
![image](https://user-images.githubusercontent.com/13120924/35395705-690e4c92-01eb-11e8-9c5b-9eb764f8df24.png)
