### ISSUE TITLE
Última revisión verticales patrones de consumo

### ISSUE THREAD

**Issue by IgnacioDomingo** [GeographicaGS/AquaGIS#205]
- [x] revisar aparición y desaparición de capas a distintos niveles de zoom con @javigil-geo 
- [x] Añadir botones zoom al mapa, como en todos los mapas de Urbo
- [x] Centrar mapa en Mairena cuando se abre
- [x] Cambia el nombre del panel de histórico de previsión a "Histórico"
- [x] Revisar leyenda del widget de previsión de consumo semanal para que el caso que esté por encima del límite sea más entendible con @javigil-geo 
- [x] Widget consumo suelo - eliminar eje Y secundario (el de la derecha)
- [ ] Widget consumo suelo - falta el último día del periodo
- [x] Widget consumo suelo - no se muestran los días q no hay datos, deben aparecer en blanco (a -- y pintarse como 0)
- [x] Widget consumo suelo - revisar si es posible redondear los valores del eje Y a unos valores más redondos por configuración. Si no es posible, no se hace

**Comment by IgnacioDomingo** [comment]
@josemazo puedes revisar "Widget consumo suelo - no se muestran los días q no hay datos, deben aparecer en blanco (a -- y pintarse como 0)" ? Parece que el endpoint no devuelve nada de los días que no tiene, debería devolver los días a null

**Comment by javigil-geo** [comment]
Ojo al Login, que ahora aparece la barra superior celeste.

**Comment by javigil-geo** [comment]
@cayetanobv estuvo mirando ayer el mapa y tiene algunas sugerencias para mejorar la visualización del mapa. Esto dará para debate y es bastante complejo, así que molaría que lo viésemos entre todos los implicados:

- No mostrar la red de abastecimiento hasta que desaparezca la capa de los sectores.
- La red de abastecimiento puede aumentar el grosor en un punto más.
- Apurar la aparición de los puntos hasta que el zoom esté mucho más cercano. Quizá un nivel antes de la desaparición de los sectores.
- Solucionar la superposición y aglomeración de iconos ¿clúster?

**Comment by IgnacioDomingo** [comment]
- [ ] Widget consumo suelo - eliminar eje Y secundario (el de la derecha). Sigue apareciendo
![image](https://user-images.githubusercontent.com/13120924/35395863-c945c2d4-01eb-11e8-9530-154977e29892.png)

- [ ] Te has dejado algún console.log, sale al cambiar el zoom
![image](https://user-images.githubusercontent.com/13120924/35395901-e09e82fe-01eb-11e8-8a39-644b27d2f387.png)

- [ ] En el login aparece la barra superior, como indica javi
![image](https://user-images.githubusercontent.com/13120924/35395992-15e239d8-01ec-11e8-88cb-dfcbe71f4fe6.png)
