### ISSUE TITLE
Simulador de datos plpgsql

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#21]
Debe funcionar de forma que agregue la información de la simulación de #16. Dos componentes:

1) Simulación del sensor: un sensor sabe el número de viviendas que abastece (una vivienda debe tener un atributo que sea sector).  A partir de los datos de consumo de vivienda + las posibles fugas + una pérdida alrededor del 20% , saca la info del sensor del sector 

2) Simulación de decremento del depósito: según el consumo demandado por los sensores  + una pérdida alrededor del 20%

**Comment by alasarr** [comment]
¿esto se ha hecho?

**Comment by alasarr** [comment]
Es importante echar un vistazo a esto donde definimos como vamos a hacer las fugas: https://github.com/GeographicaGS/AquaGIS/issues/114

**Comment by josemazo** [comment]
A la espera de las nuevas simulaciones para completar las funciones.

**Comment by josemazo** [comment]
PR https://github.com/GeographicaGS/AquaGIS/pull/149

**Comment by josemazo** [comment]
Este comentario también también tiene que ver con las tareas https://github.com/GeographicaGS/AquaGIS/issues/18, https://github.com/GeographicaGS/AquaGIS/issues/114 y https://github.com/GeographicaGS/AquaGIS/issues/117: Ya se puede usar la entidad `aq_cons.const` para lo servicios de previsión. Además ya se calculan los datos a partir de esa entidad en las entidades `aq_cons.plot` y `aq_cons.sector`. Faltarían propagar y agregar los datos de `aq_cons.const` desde el viernes (cuando la entidad tienes datos en _perfecto_ estado), y también rellenar con _invent_ previsiones.
