### ISSUE TITLE
Revisar consumo vs previsión en los casos de fuga

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#210]
Parece que cuando se decide simular un evento de fuga la diferencia entre consumo y previsión no es la que se requiere, hay que revisar por qué ocurre esto (puede que los random hagan variar demasiado o que haya que poner que los cambios son más grandes para que se asegure la fuga)

**Comment by Josmorsot** [comment]
@josemazo Los ranking de presión y caudal están devolviendo cero.
Adjunto imagen de producción.
![image](https://user-images.githubusercontent.com/7818205/35583366-04191dac-05f2-11e8-9a6e-e1bb2da0154b.png)

**Comment by josemazo** [comment]
Sobre el primer comentario (https://github.com/GeographicaGS/AquaGIS/issues/210#issue-291869766) mejor repasarlo cuando estén solo los datos simulados históricos, en incluso otro rápido a las 2 semanas, cuando todos los datos sean simulados del tiempo real.

**Comment by ignaciodomingo** [comment]
Cerramos la tarea y con el reminder de slack lo repasamos por si acaso

**Comment by josemazo** [comment]
La captura que hice ayer en Slack:

![image](https://user-images.githubusercontent.com/750907/35672363-9616d512-073e-11e8-8f77-d337eabf8678.png)
