### ISSUE TITLE
Crear nuevo simulador para súper simulaciones

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#211]
Es necesario desarrollar un nuevo simulador que permita trabajar sobre grandes cantidades de datos simulados.

@josemazo si te parece lo primero que hacemos es ver cómo llevarlo a cabo y dejarlo descrito, para que luego @alejandrohall  pueda meterle mano

**Comment by josemazo** [comment]
Recordar que cuando esté todo funcionando:

- [ ] Que estén todos los nuevos plots añadidos en DB.
- [ ] Borrar de DB los plots, las construcciones y las construcciones futuras en DB.

**Comment by josemazo** [comment]
Mergeado https://github.com/GeographicaGS/AquaGIS/pull/229 de @alejandrohall

**Comment by josemazo** [comment]
Listo, corriendo agregados de mes y medio. En general, el agregado de una hora tardan entre los 30 y 50 segundos, así que estos serán unas 15 horas. Los datos en tiempo real también están corriendo. Para mañana al mediodia estará todo listo. Además los datos en tiempo real seguirán entrando y sus agregado se irán ejecutando cuando les toquen. De todas formas durante el finde le hago un QA rápido a ver que tal.
