### ISSUE TITLE
Revisar parámetros de performance de Orion

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#212]
Revisar parámetros de performance de Orion para optimizarlo con la nueva simulación

**Comment by josemazo** [comment]
Utilizando https://fiware-orion.readthedocs.io/en/develop/admin/perf_tuning/index.html llegué a la conclusión de que la mejor config era esta (en negrita lo nuevo):

```
/usr/bin/contextBroker -multiservice -dbhost mongo -writeConcern 0 -notificationMode permanent -logLevel WARN -reqMutexPolicy none
```

Pero el `notificationMode` no funciona bien con nuestro connector, y necesita si o si la opción `fg` que se la quité, así que quedaría:

```
/usr/bin/contextBroker -fg -multiservice -dbhost mongo -writeConcern 0 -logLevel WARN -reqMutexPolicy none
```

**Comment by josemazo** [comment]
Analizando bien la situación de los conectores usan alrededor del 100% de la CPU y 2.8 GB de RAM en una instancia large (2 cores y 8 GB).

Quizá podríamos usar 2 medium (2 cores y 4 GB), una para los simuladores, y la otra para el resto (Orion con su Mongo, Connector, Processing con su Redis, API con su Redis y Postgre). En esta segunda máquina la carga estaría alrededor del 45% o 50% en idle (la mayoría usado por la Mongo) y sobre los 2 GB de memoria usada. Por el mismo precio de una large, tendríamos dos medium, una de ellas con la CPU al 50% para lidiar con la API.

**Comment by josemazo** [comment]
Instancia creada: jones_simulators, con métricas y snapshots. Cosas que hacer:

- [ ] Quitar SWAP de jones y montarla como fichero y eliminar volumen.
- [ ] Añadir SWAP a jones_simulators como fichero.
- [ ] Meter cabecera de inicio de sesión en jones_simulators.
- [ ] Reconfigurar red de jones.
- [ ] Configurar red de jones_simulators.
- [ ] Instalar Docker al completo en jones_simulators, con su carpeta apuntando al disco grande.
- [ ] Comprobar que se puede acceder al Orion de jones desde jones_simulators.
- [ ] Montar simuladores en jones_simulators, parar los de jones y arrancarlos en jones_simulators.

**Comment by josemazo** [comment]
Con las dos medium y Mongo con el `storageEngine` en `wiredTiger` va todo muy suave, olé!

jones_simulators:
![image](https://user-images.githubusercontent.com/750907/35582161-3aa72d68-05ee-11e8-9efa-decdfea71d68.png)

jones:
![image](https://user-images.githubusercontent.com/750907/35582172-42be31fe-05ee-11e8-8dc9-b429df5235de.png)

**Comment by josemazo** [comment]
Mojón. Como borré la Mongo para usar otro storage engine, borré las subcripciones y Orion no enviaba nada al conector. Al final la carga está casi igual, apenas ha mejorado. Entonces el problema no está en el pipeline Simulador -> Orion -> Mongo, sino en Mongo -> Orion - > Connector, llevándose la palma en CPU Mongo y el conector. A ver si encontramos una configuración para Mongo para que las lecturas sean más rápidas en Mongo.

**Comment by josemazo** [comment]
Índices en Mongo creados como se ve en https://fiware-orion.readthedocs.io/en/master/admin/perf_tuning/index.html#database-indexes:

```
docker exec -ti orion_mongo_1 mongo
show dbs
use orion-aljarafe
db.entities.createIndex({ "_id.id": 1 });
db.entities.createIndex({ "_id.type": 1 });
db.entities.createIndex({ "_id.servicePath": 1 });
db.entities.createIndex({ attrNames: 1 });
db.entities.createIndex({ creDate: 1 });
```

**Comment by josemazo** [comment]
Antes el grueso de la carga (siempre CPU) estaba en Mongo, aunque a veces el connector lo cogía (viendo el htop) por muy muy poco. Con los índices, ahora el conector está casí siempre arriba, y Orion y el processing se juegan el segundo puesto.

**Comment by josemazo** [comment]
Bueno, parece que el problema se va depurando. No se si haría falta otra máquina:

- Una medium con simuladores, que no es que coman una barbaridad por si solos, pero cuando tienen que escribir a Orion, al saturarse un poco este último, los simuladores también se quedan un poco atrás.
- Una medium con Orion, su Mongo, el connector y el processing con su Redis. Con todas las mejoras de performance en Orion y su Mongo, este nodo sería el cuello de botella en la entrada de datos.
- Una small (o medium) con la PostgreSQL y la Api y su Redis. Este servidor estaría holgadito para correr las queries de los servicios.

**Comment by josemazo** [comment]
Peté.

**Comment by josemazo** [comment]
Añadidas opciones: `-ipv4 -notificationMode threadpool:32:2`
- `-ipv4` hace que se olvide de IPv6 y no cree esos hilos.
- `-notificationMode threadpool:32:2` hace que cree dos hilos para enviar notificaciones y enviar batches de 32 notificaciones.

Al final se quedaría como:

```
/usr/bin/contextBroker -fg -multiservice -dbhost mongo -writeConcern 0 -logLevel WARN -reqMutexPolicy none -ipv4 -notificationMode threadpool:32:2
```

Además se han puesto todas las simulaciones dinámicas cada hora.

**Comment by josemazo** [comment]
Ha pasado un ratillo y parece que todo va muy muy bien.
