### ISSUE TITLE
Problema de performance del backend

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#213]
Ahora mismo no funcionan correctamente los servicios, tardan demasiado, y a veces ni terminan (timeout)

- [x] Aumentar máquina
- [ ] Revisar peticiones que más tardan y ver cómo optimizarlas: índices, cambiar query, etc.

**Comment by josemazo** [comment]
Lo de aumentar máquina lo estoy haciendo en https://github.com/GeographicaGS/AquaGIS/issues/212, lo desmarco.
Ya después vemos la optimización de las queries, que teniendo la CPU siempre al 100%, a ver si nos libramos.

**Comment by ignaciodomingo** [comment]
Oks, me parece bien

**Comment by josemazo** [comment]
Comprobadme mañana como va el performance, que con https://github.com/GeographicaGS/AquaGIS/issues/212#issuecomment-361676313 debería ir el back batante más fino.
