### ISSUE TITLE
Preparar documentación UPO para previsión de consumo

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#217]

**Comment by josemazo** [comment]
@ignaciodomingo echa un vistazo: https://docs.google.com/document/d/1S0jTFod5L5cLlWdiZOSTCjl8q-bMukJUQv2_a-yIPOs

Cuando acabemos la reunión, para poder añadir cosas, genero el PDF para poder enviarlo.

**Comment by ignaciodomingo** [comment]
La veo bien, esperamos a después de la reunión para cerrar la tarea

**Comment by josemazo** [comment]
Todo flamer: [Previsión de consumo.pdf](https://github.com/GeographicaGS/AquaGIS/files/1685516/Prevision.de.consumo.pdf)

Cuando estén los históricos creo la base de datos y se lo notifico.

**Comment by josemazo** [comment]
Todo flamer: [Previsión de consumo.pdf](https://github.com/GeographicaGS/AquaGIS/files/1685516/Prevision.de.consumo.pdf)

Cuando estén los históricos creo la base de datos y se lo notifico.

**Comment by ignaciodomingo** [comment]
@josemazo de esto queda algo?

**Comment by josemazo** [comment]
Si, hacer una copia de los datos en su DB y avisarlos.

**Comment by josemazo** [comment]
Documento con la contraseña nueva: [Previsión de consumo.pdf](https://github.com/GeographicaGS/AquaGIS/files/1702978/Prevision.de.consumo.pdf)

Cargando el dump.

**Comment by josemazo** [comment]
Ya está! @ignaciodomingo coméntales que hagan un dump y se monten una base de datos local. Si no la nuestra va estar chunga mientras la exploran y la usan.
