### ISSUE TITLE
Selector de sectores en mapa

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#221]
- [x] Añadir lógica para cambio de widgets según se haya seleccionado un sector o ninguno
- [x] necesitamos alguna forma de volver de la ficha de sector a mostrar los datos generales. Estamos hablando de algún botón (¿una flecha de volver?, quizás en el mapa o en la ficha (probablemente en ambos).
- [x] necesitamos también remarcar de alguna forma el sector seleccionado en el mapa, aparte de hacer zoom sobre él. Algo como cambiar la opacidad del resto de sectores, rodear el sector seleccionado por una línea continua, etc.
- [x] añadir más capas: añadimos todas las del mapa de patrones de consumo, con las mismas propiedades. La de sector usamos la que ya tiene este mapa y para parcelas las pintamos sin datos pero con alturas (la idea es sobre todo para que tenga algo de gracia el 3D)
- [x] poner labels con nombre de los sectores (ver diseño en invisio)

@javigil-geo please revisa los dos puntos que necesitan un diseño

**Comment by Josmorsot** [comment]
los tres puntos restantes quedan a la espera de revisar el estilo con @javigil-geo

**Comment by javigil-geo** [comment]
Actualizado Invision:
https://projects.invisionapp.com/d/main#/console/12071697/276594172/preview

Sobre las capas a añadir, veo bien colocar las parcelas para el 3D, y del resto de capas pintaría sólo lo que sea indudablemente necesario. En el otro vertical hay densidad de información, y que ésta sea algo más limpia no la veo mal.

**Comment by ignaciodomingo** [comment]
@Josmorsot revisa bien lo que pasa Javi, están los siguientes detalles:
- [ ] Botón de volver tanto en el mapa como en la parte de los widgets
- [ ] Se destaca el nombre del sector seleccionado en la parte de los widgets
- [ ] No sé si hay menos opacidad en el diseño al seleccionar un sector que lo que tenemos desarrollado, revísalo

**Comment by ignaciodomingo** [comment]
@javigil-geo ya está todo implementado y subido a prod, capas hemos añadido sensor y plot en gris para el 3D. Revísalo cuando puedas y si lo ves OK cierra la tarea.

**Comment by javigil-geo** [comment]
Mañana le pego un repaso en condiciones pero veo algunas cosas:
- Las labels de los distritos no están como en el diseño, aún así es posible que haya que bajar el tamaño de letra.
- En los widgets siguen saliendo los sectores coloreados.
- Hay que mantener la línea punteada de los distritos cuando no hay ninguno seleccionado.
- Ok a las flechas de volver

**Comment by ignaciodomingo** [comment]
@Josmorsot revisa lo que comenta @javigil-geo , please
Respecto a los sectores coloreados, eso todavía no está hecho, esto es sobre todo para revisar el mapa.
