### ISSUE TITLE
Revisar diseño gráfica evolución

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#226]
Hay que revisar el diseño de las gráficas de evolución del panel de fuga para darle los colores adecuados (los damos para 10 sectores como mucho, por ejemplo)
- [x] Diseño
- [x] Implementación
- [ ] Cambiar llamada para obtener nombres a: `GET /aljarafe/entities/aq_cons.sector/elements`
- [x] En la de presión, poner "Presión media", no "Nivel de caudal"

**Comment by javigil-geo** [comment]
Lo tenéis actualizado en todas las pantallas de fuga:
https://projects.invisionapp.com/d/main#/console/12071697/276594172/preview

La idea es que sólo haya un color (el de la variable); el más visible será el total/media, y el resto tendrán algo de opacidad y un blending de color (en concreto "screen").

**Comment by ignaciodomingo** [comment]
@javigil-geo ¿no queremos que cada sector se represente de forma distinta (color distinto)? ¿No puede llevar eso a confusiones?

**Comment by javigil-geo** [comment]
La idea es que mediante la leyenda que tienes abajo en el widget puedas "aislar" cada sector. De manera que activas/desactivas lo que quieres ver. Creo que eso lo tenía ya implementado Raúl en su prototipo.

**Comment by ignaciodomingo** [comment]
no está hecho el punto de cambiar la llamada
