### ISSUE TITLE
Generar tareas back y front del vertical

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#23]

**Comment by IgnacioDomingo** [comment]
Tareas creadas:
- MapBoxGL
- Vertical patrones de consumo
- Épicas para verticales de fugas, previsión energética y mantenimiento de infraestructuras (actuarán como placeholders)

Queda
- Rellenar épicas de verticales
- Aplicación mobile de mantenimiento
- ¿Recomendación de actuaciones?

**Comment by josemazo** [comment]
Añadidos los servicios para los widgets, aunque hay un pequeño problema en #37.

**Comment by IgnacioDomingo** [comment]
Épicas para verticales rellenadas.
Queda crear las tareas de la aplicación móvil de mantenimiento.

Cosas que revisar con @alasarr 
- Panel de análisis de presión en el vertical de fugas -> cómo tiene que funcionar? hablando con javi parece que es como un detalle de la fuga -> podríamos pintarlo como una ficha, al estilo urbo -> así es como lo he representado finalmente
- Vertical de fugas -> sólo tiempo real? no hay histórico? o es el panel de análisis de presión?
- Previsión de ahorro -> tiempo real? o histórico?
- Para mantenimiento, lo de preasignar un técnico según la zona, ¿es útil? Si lo es, introducirlo en metadata
- Me falta funcionalidad para editar y borrar ordenes de trabajo
- Me falta funcionalidad para eliminar documentos asociados a órdenes de trabajo
- Falta funcionalidad para gestionar los técnicos, a menos que decidamos usarlos como usuarios de Urbo (luego tendrán que logarse)
- El cálculo de personas afectadas podríamos quitarlo si es complejo (revisar metadatos y widgets)
- No incluiría nada de validar estado, complica innecesariamente
- El detalle de una orden de trabajo lo he puesto como una ficha también, sin mapa (simplifica bastante el pintar la incidencia)
- Poner estimaciones a todas las tareas

**Comment by alasarr** [comment]
Mañana vemos los dos tranquilamente e intentamos cerrar el backlog a alto nivel.

No hace falta para este año la aplicación de mantenimiento. Eso es año que viene, no?

**Comment by IgnacioDomingo** [comment]
Realmente, todo el panel es para el año que viene (teóricamente el desarrollo se termina en abril de este año), pero tendríamos que demostrar que estamos trabajando en ello. Creo que con hacer algo de la parte de mantenimiento para la justificación vamos bien, al menos el modelo de datos tiene que estar hecho 100%, ya que es parte del entregable de arquitectura que tenemos que justificar este año

**Comment by IgnacioDomingo** [comment]
- Creado vertical y tareas para aplicación móvil de mantenimiento. -> Hay que revisarlo, porque imagino que algo aparte de layout y pantallas habrá que hacer para que aparezca como una aplicación separada desde Urbo
- Estimadas todas las tareas creadas.
- Creado nueva épica de simulación de escenarios futuros, para poder dar salida a los servicios avanzados que restan. Esto hay que verlo con más detalle @alasarr , para poder ver las pantallas también con @javigil-geo
