### ISSUE TITLE
Crear modelo ontológico del sistema en Protegé

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#25]
Para justificar el entregable 1.3, es necesario crear el modelo ontológico del sistema en Protegé (https://protege.stanford.edu/)

**Comment by ignaciodomingo** [comment]
De parte de ISOIN:
- artículo que puede ser interesante para conocer el concepto y los diagramas que se pueden generar: http://www.scielo.org.co/scielo.php?script=sci_arttext&pid=S0120-62302013000400005

- ejemplo de modelo: https://drive.google.com/open?id=0B_upNBQysllib095bHNrNHlWYWttMHRCTlRwYkRZZ1IwQWZZ
![captura protege](https://user-images.githubusercontent.com/13120924/35523395-0a4f78e8-051f-11e8-8d96-d09758ed1102.png)

**Comment by isapozuelo** [comment]
Adjunto la ontología y el proyecto en Protegé:

![ontologia_red_abastecimiento_vert](https://user-images.githubusercontent.com/12248150/35683375-fbda2a14-0763-11e8-9ad7-d969a22fadea.jpg)

[ontologia.zip](https://github.com/GeographicaGS/AquaGIS/files/1685824/ontologia.zip)

**Comment by ignaciodomingo** [comment]
Yo la veo perfecta, lista para ser añadida al documento :)

**Comment by isapozuelo** [comment]
@ignaciodomingo modificado con lo que hemos hablado

![ontologia](https://user-images.githubusercontent.com/12248150/35729421-e5fb7d46-080e-11e8-9c7a-5c76c60d91eb.png)

[Third_Version_red_abastecimiento.zip](https://github.com/GeographicaGS/AquaGIS/files/1689016/Third_Version_red_abastecimiento.zip)

**Comment by isapozuelo** [comment]
@ignaciodomingo ya está el individuo en sector.

![ontologia](https://user-images.githubusercontent.com/12248150/35730472-8fcbadde-0812-11e8-96a1-07240c046f0a.png)
