### ISSUE TITLE
Arreglos

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#250]
- [x] Cambiar unidades de Previsión de consumo según usos del suelo  de Estado general a millones para que quepan los números
- [x] Revisar extraño coloreado 3D de consumo en histórico
- [x] Poner el nombre correcto al widget de "Peligro de fuga" y ponerlo en modo "now"

**Comment by Josmorsot** [comment]
Llamada que devuelve MILLONES:
**url:** _API_/aljarafe/variables/timeserie
**body:**

> {
	"agg":["SUM"],
	"vars":["aq_cons.sector.forecast"],
	"csv":false,
	"time":{
		"start":"2018-02-11T23:00:00Z",
		"finish":"2018-02-12T22:59:59Z",
		"step":"1d"
	},
	"filters":{
		"condition":{},
                 "group":"aq_cons.sector.usage"
	}
}
