### ISSUE TITLE
Revisar error en endpoint de timeserie con agregado

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#251]
Está devolviendo valores mucho más grandes que la misma petición sin agregar:

TODO: Añadir las peticiones de ejemplo

**Comment by josemazo** [comment]
Pueden ser muchas cosas. Este servicio agrega muchos puntos temporales, y los valores extremos en la **media**, la trastocan mucho. Entonces si no se comprueban todas las entidades de la serie temporal no se sabe si son muy grandes realmente o no.

A al espera quedo de las peticiones de ejemplo.

**Comment by ignaciodomingo** [comment]
Llamada que devuelve MILLONES:
`POST API/aljarafe/variables/timeserie`
```

{
"agg":["SUM"],
"vars":["aq_cons.sector.forecast"],
"csv":false,
"time":{
"start":"2018-02-11T23:00:00Z",
"finish":"2018-02-12T22:59:59Z",
"step":"1d"
},
"filters":{
"condition":{},
"group":"aq_cons.sector.usage"
}
}

````

Puedes hacer la misma sin la condition de group, la diferencia es de escala, pasa de máximos de 10k diarios (que son coherentes con el resto de endpoints y el mapa) a máximos de 10M

**Comment by josemazo** [comment]
Las fechas son de febrero! Pero bueno, voy a revisarlo en general.

**Comment by josemazo** [comment]
PR https://github.com/GeographicaGS/UrboCore-api/pull/23

**Comment by ignaciodomingo** [comment]
@josemazo Si está subido el cambio, algo no va bien, revísalo mañana con @Josmorsot , please

**Comment by josemazo** [comment]
Este PR https://github.com/GeographicaGS/UrboCore-api/pull/24 arregla eso pero con ñapa.
Hay que arreglar eso bien, para comprobar que si la variable por la que se quiere agregar no es agregada, la lea de la tabla lastdata.
