### ISSUE TITLE
Ajustes simuladores y funciones de agregación

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#258]
- [x] Cambiar los simuladores para que para 1 sector todos los días haya fuga durante 12 horas (07-19), otro sector haya anomalía de consumo durante 12 horas (07-19). El resto de sectores, deben estar bien.
- [x] Revisar si las simulaciones de previsión caudal se están calculando correctamente, ya que siempre tienen un valor de casi un 20% menores que las de uso real.
   - Falta el rendimiento (performance) en el script https://github.com/GeographicaGS/AquaGIS/blob/master/aq_cons/api/db/common/urbo_aq_cons_agg_forecast_hourly.sql, comparar con https://github.com/GeographicaGS/AquaGIS/blob/master/aq_cons/api/db/common/urbo_aq_cons_agg_realtime_hourly.sql
- [x] Revisar la simulación de presión en sectores, en los momentos en que hay fugas no parecen tener una presión muy distinta a la prevista (diferencias de 0.0001 %)
- [x] Cambiar agregación de presión para plots y sectores, de forma que se use AVG en vez de SUM. Para cambiar los valores existentes, dejarlos como están si no es posible hacer algo como dividir entre el número de sectores o algo así sencillo.
   - Ya funciona así para la tabla de agregados, pero no lo hace así para lastdata y measureand, hay que cambiar SUM por AVG para presión en los scripts https://github.com/GeographicaGS/AquaGIS/blob/master/aq_cons/api/db/common/urbo_aq_cons_propagate_to_plot.sql y https://github.com/GeographicaGS/AquaGIS/blob/master/aq_cons/api/db/common/urbo_aq_cons_propagate_to_sector.sql

**Comment by dandelea** [comment]
Preparado el script de simulaciones de anomalías en sectores.

**Comment by ignaciodomingo** [comment]
@alejandrohall tienes que revisar lo que se ha hecho aquí (mira la rama asociada)

**Comment by ignaciodomingo** [comment]
@alejandrohall es posible que algo se haya roto respecto a los datos, está fallando una llamada a timeseries:
`POST https://urbo-aquagis-backend.geographica.gs/api/aljarafe/variables/timeserie`
```
{"agg":["SUM","AVG"],"vars":["aq_cons.sector.flow","aq_cons.sector.pressure"],"time":{"start":"2018-04-06T12:00:00.000Z","finish":"2018-04-06T13:00:00.000Z","step":"1d"}}
```

Response:
`{"message":"Cannot read property 'start' of undefined","error":{}}`

Eso casi siempre es que algún dato no está bien, que faltan o algo así

**Comment by ignaciodomingo** [comment]
@alejandrohall hay que modificar la función que hace los agregados de real time, para que los agregados de plot y sector se hagan apartir de measureand y no mediante los agregados de construcción y plot (respectivamente). El agregado por measurand ya lo hace construcción, te puedes basar en él
