### ISSUE TITLE
Revisar widget de alertas de consumo cuando hay sectores sin anomalías

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#259]
- [*] Cuando un sector no tiene alerta, no debería aparecer ninguna información al respecto.
![image.png](https://images.zenhubusercontent.com/5a2e80e38a75884b908aad3c/7de95e66-0b3c-4ac4-8b55-c7db07b81b24)

- [x] También, en el sector seleccionado cuando no tiene fuga ni anomalía, debería cambiarse el texto a "No hay alerta de consumo" y no mostrar el botón de "Crear orden de trabajo".
![image.png](https://images.zenhubusercontent.com/5a2e80e38a75884b908aad3c/ae49ffbf-8317-4193-8aaf-7bb957bd9aee).

- [x] Revisar también los tamaños con el sector seleccionado, aparece scroll sin necesidad (el cambio es que la frase ahora es un poco más larga):
![image.png](https://images.zenhubusercontent.com/5a2e80e38a75884b908aad3c/7078781c-d278-4653-80c6-2f7a3241b2ca)

- [x] La gráfica de evolución para un sector seleccionado siempre está mostrando datos de un periodo determinado en vez de las últimas 24 horas:
![image](https://user-images.githubusercontent.com/13120924/36303502-a830a3c0-130c-11e8-94c6-c8c54c6084dd.png)

**Comment by ignaciodomingo** [comment]
@Josmorsot :
- [ ] La gráfica de evolución para un sector seleccionado siempre está mostrando datos de un periodo determinado en vez de las últimas 24 horas: - > esto no está solucionado
- [ ] Están ocurriendo fallos en muchos widgets, con el sector seleccionado y sin seleccionar. @alejandrohall ayuda a revisar, please

**Comment by alejandrohall** [comment]
¿Qué fallos están ocurriendo? y en cuáles

**Comment by ignaciodomingo** [comment]
Los fallos estaban relacionados con la falta de agregados, ya están solucionados.

@Josmorsot sigue quedando el de la gráfica con la fecha fija.
