### ISSUE TITLE
Finalizar E3.2. Servicios avanzados dirigidos a distribuidoras de abastecimiento urbano de agua

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#260]
Documento: https://drive.google.com/file/d/0B_upNBQyslliY1A1YVZDcElKbVRsbXZkUHl5QkozV0UwRjBr/view?usp=sharing

- [ ] Finalizar punto 2.1
- [x] Finalizar punto 3
- [x] Añadir capturas de pantalla o mockups de la implementación en Urbo de cada uno de los servicios
- [x] Eliminar referencias a consultoría externa

**Comment by isapozuelo** [comment]
@ignaciodomingo lo tienes en: AQUASIG_A3_E3.2._ServiciosAvanzadosDirigidosADistribuidoras_v3.2

**Comment by ignaciodomingo** [comment]
Detalles a corregir:
- Página 15: Uno de los objetivos principales de la actividad es proporcionar servicios que optimicen el 
consumo de agua. -> Optimicen el consumo eléctrico a la hora de llenar los depósitos de agua
- Página 33 y 34: Las capturas de pantallas correspondientes  a lo que se ha descrito anteriormente son de los paneles de patrones de consumo
- Para el punto de Predicción de Escenarios para Nuevos Desarrollos Urbanísticos, es para el que se deben poner las pantallas de simulación (pon sólo las de simulación de consumo, no las de tarificación)
- Para el punto de SIMULADOR AVANZADO DE TARIFICACIÓN DEL CONSUMO URBANO DE AGUA, poner las pantallas de tarificación de la factura eléctrica
- En las conclusiones, intenta separar los puntos y describir un poco más por cada uno de ellos. Creo que lo mejor es basarse en que cada punto del índice sea un punto en las conclusiones. Si tienes dudas, lo vemos cuando te vayas a poner

**Comment by isapozuelo** [comment]
@ignaciodomingo 
AQUASIG_A3_E3.2._ServiciosAvanzadosDirigidosADistribuidoras_v3.3
