### ISSUE TITLE
Revisar diseño general Aquagis

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#261]
![image](https://user-images.githubusercontent.com/13120924/36375891-5bb83e06-1571-11e8-94de-e8dfd743ecc9.png)

- [*] Revisar estilo general del vertical (nombre, colores, etc)
- [x] Cambiar estado general para incluir widget de fugas
- [x] En el mapa de fugas en tiempo real, cambiar el color de gris a azul oscuro (el del valor máximo del consumo o previsión en el resto de paneles)

**Comment by Josmorsot** [comment]
@ignaciodomingo (como hemos hablado antes) El nombre del vertical viene en los metadatos
