### ISSUE TITLE
Terminar E1.3

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#263]
https://drive.google.com/drive/folders/1jxWI2gpNVD4B5URkVDnQa7aaTaTYHGAU?usp=sharing

- [ ] Escribir conclusiones

**Comment by isapozuelo** [comment]
Están en esta versión del documento.
AQUASIG_A1_E1.3_Modelado de la informacion y arquitectura del sistema basada en SIGGO_v1.4
