### ISSUE TITLE
Ofrecer 3 meses de histórico para la UPO para previsión

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#264]
Replicar los datos existentes de consumo para alcancen 3 meses. Dos opciones:
- Copiar los datos existentes y cambiarle la fecha
- Ejecutar el simulador de históricos para fechas previas

**Comment by alejandrohall** [comment]
Ya he añadido los datos, hay 5 meses y medio

**Comment by ignaciodomingo** [comment]
Comentarios de la UPO:
Hemos visto que habéis ampliado los datos en la base de datos de la fase de planificación, pero revisando la base de datos de previsión, no percibimos ningún cambio en la tabla "aq_cons_const_agg_hour", que tiene registros desde "2018-01-01 00:00:00" hasta "2018-02-21 13:00:00”.

**Comment by alejandrohall** [comment]
Ya están añadidos
