### ISSUE TITLE
Cambios para justificación

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#273]
- [x] Cambiar todo lo que ponga AquaGIS a AquaSIG (revisar los logos que haya que cambiar, se los pasamos a Javi para que lo cambie)
- [x] Cambiar en el footer para que en vez de Geographica aparezca "Consorcio AquaSIG"
![image](https://user-images.githubusercontent.com/13120924/37596006-0bb72d02-2b7b-11e8-844b-f01750e54f43.png)

**Comment by Josmorsot** [comment]
![image](https://user-images.githubusercontent.com/7818205/37614293-aa67b56e-2baa-11e8-9b54-e398eac6f39b.png)
falta este logo
