### ISSUE TITLE
Crear endpoint para simulación de escenario futuro

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#277]
![image.png](https://images.zenhubusercontent.com/5a2e80e38a75884b908aad3c/e15da1dd-d851-4d84-823b-0508a3c2d035)

Este endpoint debe devolver una estructura que contenga todos los datos de tipología de construcciones en una zona.
- Parámetros de entrada: filtro de bounding box (opcional)
- Salida: Estructura que muestre por cada tipo (vivienda, industrial, etc) (campo type_name), el número de elementos que hay por cada subtipo (type_id y type_name). Para ello hay que usar las tablas aq_cons_const_simulation (son los datos) y aq_cata_const_type (indica lo que significa cada tipo) @isapozuelo puede ayudar a entender las tablas. El objetivo es que al front le llegue toda la info que necesita.

Por motivos de referencia, puede ser útil mirar http://iatdev.isoin.es/aquasig-web/docs en la parte de cálculo de escenarios futuros

**Comment by josemazo** [comment]
Cosas sobre la simulacion:
- ¿La tabla aq_cons_const_simulation debería ser `aq_cata_const_simulation`?
- ¿Que relación guardan la tabla anterior y `aq_cata_const_type`?
- Hay que meter las dos tablas anteriores en los metadatos.

**Comment by josemazo** [comment]
@dandelea ⬆️

**Comment by ignaciodomingo** [comment]
No consigo hacerlo funcionar sin bbox.
Este es la REQUEST:
`POST /aljarafe/aq_simul/simulation/count`
```
{
  "filters": {
  	
  }
}
```
RESPONSE
```
{
    "message": "Cannot read property 'bbox' of undefined",
    "error": {}
}
```

**Comment by dandelea** [comment]
Checked

**Comment by ignaciodomingo** [comment]
El problema estaba en la forma de enviar el body, que no había indicado yo que era JSON.
