### ISSUE TITLE
Dar acceso a UPO para acceder a BD de Aquagis

### ISSUE THREAD

**Issue by IgnacioDomingo** [GeographicaGS/AquaGIS#28]
La ip a la que dar acceso es:
193.147.188.5

**Comment by josemazo** [comment]
Está la base de datos abierta (0.0.0.0), que lo hice para que Isa tuviera acceso desde Isoin y no lo cambié. He perdio mis claves de AWS y no puedo volver a ponerla a las nuestras. Así que cuando lo restaure pongo también la de la UPO.

**Comment by IgnacioDomingo** [comment]
Cliente comenta esto:
Al realiar la consulta SELECT * FROM tank_sector;
nos devuelve el error:
SQL Error [42501]: ERROR: permission denied for schema phase1_v1  Position: 15

Parece un problema de permisos

**Comment by josemazo** [comment]
Arreglado.

**Comment by IgnacioDomingo** [comment]
gracias josema
