### ISSUE TITLE
Sin datos de Orion en el vertical de consumo

### ISSUE THREAD

**Issue by dandelea** [GeographicaGS/AquaGIS#280]
Orion llevaba hoy 7 días caído y no ha estado dando datos a consumo. Por lo tanto muchas de las funcionalidades ahora están vacías o rotas.

Orion se ha vuelto a levantar pero desconozco si este problema se arreglará con un par de días o podría requerir alguna atención más. Los datos en tiempo real funcionan correctamente.

**Comment by josemazo** [comment]
Puede ser del cálculo de agregados.

**Comment by dandelea** [comment]
Se han replicado los datos de la semana anterior para esta semana en cuestión. Parece que los widgets del vertical han vuelto a funcionar. Cierro la issue.
