### ISSUE TITLE
Problemas de integración del vertical Simulación con la arquitectura de metadatos actual

### ISSUE THREAD

**Issue by dandelea** [GeographicaGS/AquaGIS#281]
El vertical de simulación (`aq_simul`) ya está completado. Se ha probado en mi máquina que los endpoints funcionen correctamente con las tablas que se han especificado. Pero existen algunos problemas a la hora de integrarlos con la aplicación de front que se haya actualmente en `jones.geographica.gs`.

Este vertical es realmente un paquete de funciones que carece de variables propias de sensores como ocurren en los otros verticales. Actualmente se han registrado el vertical en `metadata.categories` y las tablas estáticas (las simulaciones) en `metadata.entities`, pero nada en `metadata.variables`, por esta razón anterior. Front realiza una consulta para saber que verticales existen, la cual hace una interseccion de estas tres tablas, lo cual da ningun resultado para el vertical `aq_simul`, y por lo tanto éste no existe para front.

Seguí el ejemplo de consumo (`aq_cons`) cuando no debía incluir las variables de tablas auxiliares en los metadatos. A este problema le encuentro varias soluciones.

- Registrar las variables "estáticas" (valores simulados sin semántica de posición o tiempo) como variables. Creo que no habría mayor repercusión pero no cumple con el estándar de la arquitectura actual.
- Retocar la consulta del endpoint disponible para tener en cuenta este tipo de casos. Habría que estudiar el resto de endpoints de metadata para no romper nada.
- Añadir este vertical como una extensión al vertical de consumo. Pongamos que se añade una pestaña nueva. Desconozco el impacto de front de esta opción.

**Comment by ignaciodomingo** [comment]
@josemazo ¿qué opinas? Yo creo que con registrar una variable estática dummy sería suficiente para esto.

**Comment by ignaciodomingo** [comment]
Tras hablar con Josema, lo hacemos con una variable estática dummy.
