### ISSUE TITLE
Issues vertical escenarios futuros

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#300]
tarificación
- [x] añadir € a los distintos valores del tooltip
- [x] formatear números a dos decimales todos
- [x] añadir consumo a tooltip (con su unidad)

consumo futuro
- [x] leyenda aparece muy abajo
- [x] hacer que leyenda esté abierta por defecto (debe ser una configuración)
- [x] hacer que sea clickable para desplegar el nombre entero de VIVIENDA, no solo la flecha
- [x] formatear total del agua, que tenga separadores y eso y máximo 2 decimales
- [x] quitar botón 3d
- [x] formatear número de viviendas
- [x] los labels usados para los tipos dentro de vivienda, edificio, etc, no son los correctos, revisar http://iatdev.isoin.es/aquasig- [ ]web/docs (aunque creo que el endpoint te devuelve algo tb)
- [x] al modificar el número de edificios de cada tipología, no se actualiza el total que aparece junto a vivienda, edificio, etc

**Comment by borjaeguia** [comment]
Lista de tipos a modificar en base de datos:

**Edificio**
10 Número de habitantes
20 Número de habitantes
30 Número de habitantes
40 Número de habitantes
50 Número de habitantes
60 Número de habitantes

**Instalación deportiva**
15 Número de usuarios
50 Número de usuarios
200 Número de usuarios

**Industria**
1 Consumo (m3/día)
5 Consumo (m3/día)
10 Consumo (m3/día)
50 Consumo (m3/día)
100 Consumo (m3/día)
225 Consumo (m3/día)

**Vivienda**
2 Número de personas
3 Número de personas
4 Número de personas
5 Número de personas
6 Número de personas
7 Número de personas

**Uso terciario**
50 Superficie (m2)
150 Superficie (m2)
200 Superficie (m2)

**Hospedaje**
100 Número de camas
150 Número de camas
200 Número de camas

**Piscina**
1 Piscina

**Comment by ignaciodomingo** [comment]
hecho en el back

**Comment by ignaciodomingo** [comment]
@borjaeguia 
Cosas que faltan
- [ ] hacer que leyenda esté abierta por defecto (debe ser una configuración) (estaba antes)
- [ ] falta el botón de bbox

**Comment by ignaciodomingo** [comment]
@borjaeguia cosas que fallan:
- [ ] falta el botón de bbox
