### ISSUE TITLE
Modificar presentación Justificación Anualidad 2017

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#310]
Seguir detalles en: https://docs.google.com/document/d/1mUVewk4dRYn0w_rEnc_zo7W88YtMyMqEUPwtJDFzrO8/edit?usp=sharing

**Comment by isapozuelo** [comment]
@ignaciodomingo incluido el logo en el último Post de AQUASIG
https://geographica.gs/es/blog/que-es-smart-water/
