### ISSUE TITLE
Layout AquaGIS

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#36]
Hay que crear un layout como en CEDUS. Esto lo que hace es cargar un CSS.

Hay que hacer algo para mejorar la cabecera y parar el sistema de IFs.

**Comment by alasarr** [comment]
Cosas como estás hay que quitarlas del código del core:
https://github.com/GeographicaGS/UrboCore-www/blob/master/src/js/template/header_template.html#L4

Cosas como estas también:
https://github.com/GeographicaGS/UrboCore-www/blob/master/src/js/template/footer_template.html#L25

**Comment by alasarr** [comment]
Como funciona el layout es que se añade el atributo definido en [Config](https://github.com/GeographicaGS/UrboCore-www/blob/master/src/js/Config.production.js#L29) al body al [inicializar](https://github.com/GeographicaGS/UrboCore-www/blob/master/src/js/App.js#L445). Luego es cuestión de definir reglas en CSS que hagan matching: https://github.com/GeographicaGS/urbo-cedus/blob/master/theme-cedus/www/css/styles.less#L1

**Comment by neokore** [comment]
Quedan pendientes algunos detalles:

- [ ] Login. Cambia colores y logo y que @javigil-geo te dé el OK.
- [ ] Algunos colores siguen siendo Urbo: 
      <img width="283" alt="imagen" src="https://user-images.githubusercontent.com/938057/34672688-bc3325ba-f47f-11e7-81ce-385b3bbfc553.png">
      <img width="176" alt="imagen" src="https://user-images.githubusercontent.com/938057/34672824-3a92c26c-f480-11e7-8207-3386fad72f79.png">
- [ ] Lista de ámbitos sigue siendo Urbo:
      <img width="698" alt="imagen" src="https://user-images.githubusercontent.com/938057/34672794-1ab68e06-f480-11e7-9ade-f1428019e5e0.png">
- [ ] Los widgets siguen siendo color Urbo:
      <img width="768" alt="imagen" src="https://user-images.githubusercontent.com/938057/34672873-6c4467de-f480-11e7-95bc-285867c2f0c9.png">
- [ ] Scroll también parece Urbo style:
      <img width="116" alt="imagen" src="https://user-images.githubusercontent.com/938057/34672911-ab301880-f480-11e7-8861-d4a2ee2f7e68.png">
- [ ] Posible descuadre:
      <img width="219" alt="imagen" src="https://user-images.githubusercontent.com/938057/34673295-0eecb5b2-f482-11e7-878c-b460966250b3.png">

**Comment by javigil-geo** [comment]
Os dejo el login adaptado por aquí:
https://projects.invisionapp.com/d/main#/console/12071697/272481755/preview

**Comment by neokore** [comment]
Segunda revisión de interfaz:
- [ ] Aspecto de selector de ámbitos: El diseño original es blanco y el que veo es azul.
       ![imagen.png](https://images.zenhubusercontent.com/57b2efa6e40e5714b16d6766/6bc623dc-99cb-4568-a51e-5211bcd10f85)
- [ ] Bordes en los widgets: en el diseño original no existen.
       ![imagen.png](https://images.zenhubusercontent.com/57b2efa6e40e5714b16d6766/2bb3c0fd-3c3e-4323-9fa2-d2561d1a59ff)
- [ ] Refinar el aspecto de la pastilla selectora de sección. Bordes y color de texto.
       ![imagen.png](https://images.zenhubusercontent.com/57b2efa6e40e5714b16d6766/94757992-f028-4fb0-b45c-b3477885da51)
- [ ] Algunos elementos del selector de fechas siguen siendo Urbo style (botones de flechas e icono de calendario en modo activo al menos):
       ![imagen.png](https://images.zenhubusercontent.com/57b2efa6e40e5714b16d6766/0451eeda-b607-480f-bbe8-87b5854ab0e6)

**Comment by IgnacioDomingo** [comment]
@eamador ¿puedes revisar lo que comenta raúl, por favor?

**Comment by eamador** [comment]
He actualizado el PR, aunque hay dos puntos que creo deberian ser revisados por @javigil-geo, los dos puntos son los que están relacionado con el estilo de los botones. 

![captura de pantalla 2018-01-11 a las 9 40 55](https://user-images.githubusercontent.com/9006480/34815958-a5fdc062-f6b3-11e7-9002-63916dccf207.png)
![captura de pantalla 2018-01-11 a las 9 40 48](https://user-images.githubusercontent.com/9006480/34815959-a62f134c-f6b3-11e7-84e6-9332069e28d9.png)

Please @javigil-geo alguna sugerencia?
