### ISSUE TITLE
Widget: Previsión de consumo próxima semana

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#37]
![Captura de pantalla 2017-12-22 a las 9.39.26.png](https://images.zenhubusercontent.com/57b2c068e40e5714b16d6586/d6b00c37-73c1-4c6f-9136-0c5684c9dda1)

**Comment by alasarr** [comment]
Añadir ejemplo de llamada a la API

**Comment by josemazo** [comment]
Parece hay servicio para este widget, habría que hacerlo, por lo de agrupar una variable por una otra.

Se podría hacer una llamada por cada uso del agua, pero los filtros de los payload solo funcionan para una sola tabla. Me explico: el consumo es un agregado (obtenido a través del caudal) y está en su tabla, y el uso del suelo es una variable de catálogo y está en las tablas de catálogo y lastdata. Si se arregla esto, se podría hacer una llamada a: `/aljarafe/variables/aq_cons.sector.consumption/historic` con este payload:

```json
{
  "agg": "SUM",
  "time": {
    "start": "2018-01-01T00:00:00Z",
    "finish": "2018-01-08T00:00:00Z"
  },
  "filters": {
    "condition": {"usage__eq": "domestic"}
  }
}
```

**Comment by alasarr** [comment]
Propongo dos opciones:

1) Hacer un endpoint específico de este vertical.
2) Que se añada al agregado un capo que sea el uso.

Evitaría hacerlo en front.

**Comment by IgnacioDomingo** [comment]
@josemazo lo hablamos cuando vuelvas y vemos la solución

**Comment by josemazo** [comment]
Vería la opción 1, pero no siendo específico, si no genérico.

**Comment by IgnacioDomingo** [comment]
lo veo bien, creada #119 para esto

**Comment by IgnacioDomingo** [comment]
La llamada a la API es:

`POST /aljarafe/variables/aq_cons.const.forecast/historic`

```
{
  "agg": "SUM",
  "time": {
    "start": "2018-01-01T00:00:00Z",
    "finish": "2018-01-08T00:00:00Z"
  },
  "filters": {
    "condition": {},
    "group": "aq_cons.const.usage"
  }
}
```

**Comment by IgnacioDomingo** [comment]
Cosas que he encontrado:
- [ ] Cuando recargo o navego a veces se queda cargando el widget.
- [ ] Las leyendas se pisan y quedan raras, revisar
![image](https://user-images.githubusercontent.com/13120924/35100216-44479fc0-fc5b-11e7-9b7a-cf732cb04a03.png)
- [ ] No soy capaz de ver si lo está pintando bien, cambiar la escala para que pinte algo legible (a 10 de máximo, por ejemplo)

**Comment by padawannn** [comment]
Esto no está funcionando bien @Josmorsot lo miro yo.

**Comment by padawannn** [comment]
Vale, ya está arreglado. Lo subo cuando @IgnacioDomingo me acepte un PR en urbo core
