### ISSUE TITLE
Widget: Consumo total semana anterior

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#40]
![Captura de pantalla 2017-12-22 a las 9.44.31.png](https://images.zenhubusercontent.com/57b2c068e40e5714b16d6586/09222143-bc3c-4c8c-917d-9fb40e147440)

**Comment by josemazo** [comment]
Dos posibles servicios:

- GET `/aljarafe/variables/aq_cons.sector.consumption?agg=sum&start=2018-01-01T00:00:00Z&finish=2018-01-08T00:00:00Z`

- POST `/aljarafe/variables/aq_cons.sector.consumption/historic` con este payload:
```json
{
  "agg": "SUM",
  "time": {
    "start": "2018-01-01T00:00:00Z",
    "finish": "2018-01-08T00:00:00Z"
  }
}
```

**Comment by alasarr** [comment]
Creo que mejor el POST

**Comment by alasarr** [comment]
Importante, no queremos mostrar los últimos 7 días si no la semana anterior. Que muestre siempre de lunes al domingo anterior.

**Comment by IgnacioDomingo** [comment]
@Josmorsot lo que está subido se queda cargando
![image](https://user-images.githubusercontent.com/13120924/34941310-8139fcee-f9f3-11e7-88d0-042bb2c09644.png)

**Comment by IgnacioDomingo** [comment]
@Josmorsot cuando se refresca la pantalla o se le da a atrás no carga (la petición parece hacerla bien)
![image](https://user-images.githubusercontent.com/13120924/35044035-1e83ead6-fb8f-11e7-8d9e-5eb741147d87.png)

**Comment by Josmorsot** [comment]
Esta corregido, se interrumpia la ejecucion al fallar el otro widget
