### ISSUE TITLE
Widget: mapa de patrones de consumo

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#41]
Tiene que ser un mapa que muestre los sensores de los sectores.

![Captura de pantalla 2017-12-22 a las 9.47.53.png](https://images.zenhubusercontent.com/57b2c068e40e5714b16d6586/6770ba7d-928a-4f1a-b16a-9b27517b9e54)

Completar: Añadir el servicio de puntos genéricos.

**Comment by josemazo** [comment]
Estos datos se obtienen con GET `/aljarafe/devices/map?entities=aq_cons.sector`

**Comment by IgnacioDomingo** [comment]
- [ ] @Josmorsot no puede usarse Carto para esto, hay que usar mapbox.
- [ ] Como bonus track, eliminar la mención a Carto del footer

**Comment by Josmorsot** [comment]
Mañana te cuento sobre esto

**Comment by Josmorsot** [comment]
@IgnacioDomingo

**Comment by Josmorsot** [comment]
@IgnacioDomingo como te he dicho, las llamadas a Carto vienen del estilo de mapa

`},
  "glyphs": "https://tiles.basemaps.cartocdn.com/fonts/{fontstack}/{range}.pbf",
  "layers": [
    {`
