### ISSUE TITLE
Widget: previsión consumo según usos

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#43]
![Captura de pantalla 2017-12-22 a las 9.55.59.png](https://images.zenhubusercontent.com/57b2c068e40e5714b16d6586/80d8973f-8b28-459a-96a8-89630125fe4e)

Poner usos a secas, no uso del suelo

TODO: completar con el enpoint a llamar

**Comment by josemazo** [comment]
Este sería como #42 pero con algo más en el payload: POST `/aljarafe/variables/timeserie`
```json
{
  "agg": ["SUM"],
  "vars": ["aq_cons.sector.consumption"],
  "time": {
    "start": "2018-01-01T00:00:00Z",
    "finish": "2018-01-08T00:00:00Z",
    "step": "1d"
  },
  "filters": {
    "condition": {"usage__eq": "domestic"}
  }
}
```

**Nota**: Aquí si funciona el filtro por columna, no como con el servicio propuesto en #37.

**Comment by alasarr** [comment]
Mil gracias @josemazo

**Comment by alasarr** [comment]
Antes de hacer esto debemos ver como se agrupan en cada step del timeserie. Ese endpoint devuelve los datos de cada día de todos, no separado por cada uso.

**Comment by josemazo** [comment]
Si, viendo como se resuelve #37, aplicamos lo mismo aquí.

**Comment by IgnacioDomingo** [comment]
lo resolvemos como #37, he creado la tarea #120 para ello

**Comment by josemazo** [comment]
En esta rama está listo, voy a por el otro.

**Comment by IgnacioDomingo** [comment]
La llamada a usar para este widget es:
POST /aljarafe/variables/timeserie
```
{
  "agg": ["SUM"],
  "vars": ["aq_cons.const.forecast"],
  "time": {
    "start": "2018-01-01T00:00:00Z",
    "finish": "2018-01-08T00:00:00Z",
    "step": "1d"
  },
  "filters": {
    "condition": {},
    "group": "aq_cons.sector.usage"
  }
}
```
