### ISSUE TITLE
MapboxGL GeoJSON layer

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#47]
Realizar capa GeoJSON. Probarlo primero con una capa, por ejemplo sensores o la red de distribución.
Documentación de la API que devuelve las entidades:
https://geographicags.github.io/Urbo-docs/reference/maps/

Para obtener los sectores de aljarafe sin aplicar ningún filtro:
URL: https://urbo-aquagis-backend.geographica.gs/api/aljarafe/maps/aq_cons.sector/now
POST
Body: 
{
   "filters": {}
}

Estilos:

- Puntos: icono y color.
- Líneas: opacity line, opacity line color.
- Polígono: stroke, fill, opacity.

**Comment by alasarr** [comment]
Falta por añadir la interactividad de las capas. Un featureClick y un featureOver.

El popup de interactivity debe recibir una lista de properties a mostrar. También debemos tener la posibilidad de añadir una label para el popup. Por defecto, la label es el nombre del campo

**Comment by IgnacioDomingo** [comment]
![image](https://user-images.githubusercontent.com/13120924/35044148-95fe7554-fb8f-11e7-9ed6-d12c91cef1bd.png)
@Josmorsot revisa esto, no debería salir por encima
