### ISSUE TITLE
Mapbox GL WMTS layer

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#48]
Sacar los datos de WMTS PNOA

**Comment by IgnacioDomingo** [comment]
@alasarr de dónde sacamos los datos para la capa? del servicio wms de catastro? o lo incluimos en nuestra postgis y lo servimos desde ahí? Para la segunda opción, para un piloto no hay problema, pero para españa en general habría que descargar municipio a municipio (o hablamos con ellos para pedir una descarga más masiva)

**Comment by IgnacioDomingo** [comment]
Cambiar nombre de pnoa a Ortofoto
