### ISSUE TITLE
Endpoint para obtener entidades como GeoJSON

### ISSUE THREAD

**Issue by alasarr** [GeographicaGS/AquaGIS#49]
Comprobar si existe y si se pasan todos los atributos

**Comment by josemazo** [comment]
El servicio GET `/:scope/devices/mapentities?entities=parking.spot&geojson=true` (ejemplo para parking spots) devuelve una lista de GeoJSONs, no una feature collection. Si este nos es válido, pues listo, si no, se cambia.

**Comment by josemazo** [comment]
PR https://github.com/GeographicaGS/UrboCore-api/pull/13 para arreglar el servicio para ciertas entidades, como parking spot

**Comment by josemazo** [comment]
Parece que no tenemos ningún servicio así.

Necesitamos un servicio de variable (para pedir la previsión entre dos fechas, y otros filtros), que las agrupe por entidad y las agregue por lo que se pida. Pero además, debe devolver otros valores por entidad, como la geometría (básico aquí para crear el GeoJSON), el id_entity... quizás el lastdata entero.

**Comment by IgnacioDomingo** [comment]
Las capas que hay que devolver:
Sensor.
Depósito.
Sectores. - este es un área
Red de abastecimiento.
Edificios.
Catastro (WMTS)

**Comment by josemazo** [comment]
PR https://github.com/GeographicaGS/UrboCore-api/pull/16 con el servicio listo.

**Comment by josemazo** [comment]
Sobre las capas, la de catastro ya está mapeada a la de edificios (y otra tabla extra) por Isa.

**Comment by josemazo** [comment]
Las entidades _estáticas_ que se pueden pedir como GeoJSON son:

- aq_cata.connections_line
- aq_cata.connections_point
- aq_cata.hydrant_line
- aq_cata.hydrant_point
- aq_cata.plot
- aq_cata.plot_structure
- aq_cata.supply_line
- aq_cata.supply_point
- aq_cata.sector
- aq_cata.sensor
- aq_cata.tank
- aq_cata.valve_line
- aq_cata.valve_point
- aq_cata.well_line
- aq_cata.well_point
