### ISSUE TITLE
Duda UPO pump_flow

### ISSUE THREAD

**Issue by IgnacioDomingo** [GeographicaGS/AquaGIS#50]
¿ El caudal de la tubería de un tanque (pump_flow) viene dado en metros cúbicos hora (m3/h) como indica el documento
o en realidad son metros cúbicos por segundo (m3/sg) ? A nosotros nos cuadra más m3/sg puesto que, de otro modo, no 
daría tiempo a llenar el tanque en un día y el consumo sobrepasaría la capacidad del tanque. Te pongo una imagen 
de unos cálculos hechos a mano para la planificación de aperturas de tubería del día 11/12/2017; como puedes ver, 
en el caso de que el caudal sea 1 m3/hora y 1 m3/minuto siempre nos quedaríamos sin reservas de agua incluso abriendo las tuberías
todo el día; sin embargo, en el caso de que el caudal sea de 1 m3/sg tenemos más margen de maniobra para optimizar las aperturas y cierres
en base al consumo y el precio de la electricidad.

<img width="1320" alt="captura de pantalla 2017-12-26 a las 15 15 17" src="https://user-images.githubusercontent.com/13120924/34358725-a27c00b0-ea52-11e7-8f76-91787fc2378b.png">

**Comment by josemazo** [comment]
Si, el valor parece que correspondía con m3/s cuando deberían ser m3/h. Cambio el valor en BD para que se corresponda con m3/h.
