### ISSUE TITLE
Patrones de consumo - histórico de previsiones

### ISSUE THREAD

**Issue by IgnacioDomingo** [GeographicaGS/AquaGIS#57]
![image](https://user-images.githubusercontent.com/13120924/34431449-86ec9494-ec6f-11e7-9f4d-bf6841f914f8.png)

No incluir widget de temperatura

**Comment by alasarr** [comment]
Es el mismo que #56 pero con el selector de tiempo

**Comment by IgnacioDomingo** [comment]
No funciona bien, se queda muy rayado al cambiar las fechas, revisar errores de consola

**Comment by IgnacioDomingo** [comment]
- [ ] Pintar sector transparente cuando valor sea null
- [ ] Widget de previsión de consumo semanal no cambia de variable
- [ ] Darle mejor estilo al selector

**Comment by IgnacioDomingo** [comment]
- [ ] El widget de previsión de consumo semanal muestra un valor de la escala cuando es --. Javi lo cambió.
- [ ] El widget de previsión de consumo semanal muestra -- cuando se cambia a consumo cuando hay datos (comparando con el mapa)
- [ ] Estilo del selector
