### ISSUE TITLE
MapBoxGL Implementar el resto de capas GeoJS

### ISSUE THREAD

**Issue by IgnacioDomingo** [GeographicaGS/AquaGIS#61]
Estas son todas las capas GeoJS a implementar:
**Sensor**.
 ~aq_cata.sensor~

**Depósito (evento)**.
 ~aq_cata.tank~
 
**Sectores. - este es un área (evento)**
 ~aq_cata.sector (no usar, usar el dinámico)~

**Red de abastecimiento**
 ~aq_cata.connections_line~
 ~aq_cata.connections_point~

**Hidrantes**
 ~aq_cata.hydrant_line~
 ~aq_cata.hydrant_point~

**Acometidas**
 ~aq_cata.supply_line~
 ~aq_cata.supply_point~

**Válvulas**
 ~aq_cata.valve_line~
 ~aq_cata.valve_point~

**Pozos**
 ~aq_cata.well_line~
 ~aq_cata.well_point~

**Edificios (evento)**.
 ~aq_cata.plot~
 ~aq_cata.plot_structure~

**Comment by IgnacioDomingo** [comment]
@javigil-geo, necesitamos diseño para cada una de las capas y elementos, si quieres ver cómo quedan, tenemos el modelo en qgis: https://drive.google.com/open?id=1k9BwuSc-eNKscExJienvOFGXknXobLgG

**Comment by javigil-geo** [comment]
Adjunto pantalla de invision con una prueba de cartografía:
https://projects.invisionapp.com/d/main#/console/12071697/272700251/preview

Y la referencia de colores:
https://projects.invisionapp.com/d/main#/console/12071697/272446564/preview

Los iconos están exportados en la carpeta IMG/cartografia/
En zoom lejanos se deberá ver solo el punto con el color asignado, y a cierto nivel de cercanía aparecerá el icono.

**Comment by alasarr** [comment]
Falta la interactivity

**Comment by IgnacioDomingo** [comment]
Por resumir:
- [ ] Añadir interactivity
- [ ] Cambiar aq_cata.plot y aq_cata.plot_structure por aq_cons.const y aq_cons.plot

**Comment by IgnacioDomingo** [comment]
- [ ] @Josmorsot el tooltip de hidrantes dice "Acometida" en vez de "Identificador"
![image](https://user-images.githubusercontent.com/13120924/35045338-d3521e02-fb93-11e7-9678-f0a5781a8f06.png)

- [ ] Y no sé si hay alguna forma de dar prioridad al click sobre unas capas antes que a otras. Es decir, si hago click sobre una parcela, que me salgan los datos de la parcela y no los del sector.

**Comment by Josmorsot** [comment]
@IgnacioDomingo al pulsar sobre una parcela se abren los popups de parcela y sector. La parcela queda por encima, pero no hay manera sencilla de evitar la propagación
