### ISSUE TITLE
Mapa de fugas

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#68]
Esta información se muestra en el vertical de patrones de consumo

![image](https://user-images.githubusercontent.com/13120924/34513955-25d6b52c-f06b-11e7-898b-ce24137fbcef.png)

- [x] Añadir mapa de coropletas según campo leak_status del servicio.

- [x] Añadir la leyenda.

- [ ] ~Añadir tooltip.~

- [x] Al hacer click centrar en el sector. Hacer que los widgets del panel cambien si has hecho click en un sector y estás en modo sector.

El selector de fecha de la imagen no aplica.

**Comment by alasarr** [comment]
Usa el servicio genérico de geoJSON donde tendrá un campo leak_status.

**Comment by alasarr** [comment]
El selector de fecha no aplica.

**Comment by IgnacioDomingo** [comment]
@javigil-geo necesitamos diseño para dos cosas:
- [ ] necesitamos alguna forma de volver de la ficha de sector a mostrar los datos generales. Estamos hablando de algún botón (¿una flecha de volver?, quizás en el mapa.
- [ ] necesitamos también remarcar de alguna forma el sector seleccionado en el mapa, aparte de hacer zoom sobre él. Algo como cambiar la opacidad del resto de sectores, rodear el sector seleccionado por una línea continua, etc.

**Comment by ignaciodomingo** [comment]
he movido los dos puntos pedidos a javi gil y la lógica de cambiar los widgets según la selección a la tarea #221
