### ISSUE TITLE
Endpoint para Avisos de fugas

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#71]
Este endpoint debe devolver información sobre las fugas y anomalías de consumo que se estén produciendo actualmente:
![image](https://user-images.githubusercontent.com/13120924/34514184-5a75a850-f06c-11e7-8ecc-14381c071daf.png)

Añadir información de pérdida de suministro para dar salida al widget
![image](https://user-images.githubusercontent.com/13120924/34515133-fe3c3f2c-f070-11e7-807b-305b8965e4df.png)

TODO: Definir reference. Que sea custom.

Habría que coger los registros sin fecha fin.

Primera versión sin pérdida de suministro.

**Comment by josemazo** [comment]
Tendría que revisar los metadatos, porque quizá no hiciera falta endpoint, o si hiciera falta, dejarlo también lo más Urbo posible.

**Comment by josemazo** [comment]
También comprobar que esto https://github.com/GeographicaGS/AquaGIS/issues/79#issuecomment-361246948 funciona para https://github.com/GeographicaGS/AquaGIS/issues/79

**Comment by josemazo** [comment]
He movido el texto también como variable Urbo, voy a ver si hay un servicio para obtener el texto por entidad.

**Comment by josemazo** [comment]
Modificado un endpoint genérico:

```
GET /aljarafe/entities/aq_cons.sector/elements?variables=aq_cons.sector.leak_status,aq_cons.sector.leak_rule
```

Este servicio, sin el query string te devolvería también los nombres de los sectores, que comentamos ayer que podría haber un servicio, pues este también nos serviría.

**Comment by josemazo** [comment]
PR https://github.com/GeographicaGS/UrboCore-api/pull/21

**Comment by ignaciodomingo** [comment]
Eso te devuelve el last data, ¿correcto?

**Comment by ignaciodomingo** [comment]
confirmado

**Comment by josemazo** [comment]
Si!
