### ISSUE TITLE
Widget de sectores con mayor caudal

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#72]
Este widget es para el modo general, sin seleccionar sector
![image](https://user-images.githubusercontent.com/13120924/34514296-06f2a394-f06d-11e7-8738-20414dba4945.png)
TODO: incluir info de endpoint

En esta primera versión quitar la ordenación. Hay un widget de ranking o tabla para esto

**Comment by Josmorsot** [comment]
Widget: http://urbo.geographica.io/es/distrito_telefonica/transport/dashboard

**Comment by IgnacioDomingo** [comment]
endpoint:
`POST /aljarafesa/variables/ranking/now`
````
{
  "vars": [
    "aq_cons.sector.name",
    "aq_cons.sector.flow"
  ],
  "var_order": "aq_cons.sector.flow",
  "order": "desc",
  "limit": 5,
  "filters": {
  }
}
````
