### ISSUE TITLE
Widget de sectores con mayor presión

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#73]
![image](https://user-images.githubusercontent.com/13120924/34514318-3200fe64-f06d-11e7-95b5-2d444425a1bc.png)
TODO: añadir info de endpoint

**Comment by IgnacioDomingo** [comment]
endpoint:
`POST /aljarafesa/variables/ranking/now`
````
{
  "vars": [
    "aq_cons.sector.name",
    "aq_cons.sector.pressure"
  ],
  "var_order": "aq_cons.sector.pressure",
  "order": "desc",
  "limit": 5,
  "filters": {
  }
}
````
