### ISSUE TITLE
Widget de caudal total

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#75]
Este widget es para el modo general, sin seleccionar sector
![image](https://user-images.githubusercontent.com/13120924/34514366-7183f03c-f06d-11e7-90cf-a45f0daef6ce.png)
TODO: Añadir info de endpoint. https://geographicags.github.io/Urbo-docs/reference/variables/#post-scopevariablesid_variabledevices_group_timeserie

**Comment by alasarr** [comment]
Preguntar a @neokore si esto está desarrollado.

**Comment by neokore** [comment]
Con distintos colores está desarrollado seguro, pero con distintos tipos de lineas no, aún así, podrían aprovecharse los cambios que se realicen en #80. Diría que 3 horas teniendo eso en cuenta.

**Comment by IgnacioDomingo** [comment]
`POST /aljarafe/variables/aq_cons.sector.flow/devices_group_timeserie`
```
{
  "agg": "AVG",
  "time": {
    "start": "2018-01-29T00:00:00Z",
    "finish": "2018-01-29T23:59:59Z",
    "step": "1h"
  },
  "filters": {
  },
  "groupagg": "true"
}
```

**Comment by Josmorsot** [comment]
Cambiar el estilo del widget por el planteado por @neokore 

![image](https://user-images.githubusercontent.com/7818205/35576815-38498fec-05e0-11e8-9890-ea0d5ce6e809.png)

**Comment by Josmorsot** [comment]
#75 y #76 quedan a la espera de revisar el diseño con @javigil-geo

**Comment by ignaciodomingo** [comment]
Las cerramos, he abierto #226 para revisar el diseño
