### ISSUE TITLE
Widget de presión media

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#76]
Este widget es para el modo general, sin seleccionar sector
![image](https://user-images.githubusercontent.com/13120924/34514395-900af352-f06d-11e7-8959-649954da2451.png)
TODO: Añadir info de endpoint

**Comment by IgnacioDomingo** [comment]
`POST /aljarafe/variables/aq_cons.sector.pressure/devices_group_timeserie`
```
{
  "agg": "AVG",
  "time": {
    "start": "2018-01-29T00:00:00Z",
    "finish": "2018-01-29T23:59:59Z",
    "step": "1h"
  },
  "filters": {
  },
  "groupagg": "true"
}
```

**Comment by ignaciodomingo** [comment]
Las cerramos, he abierto #226 para revisar el diseño
