### ISSUE TITLE
Widget de análisis de fuga

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#78]
Este widget es para el modo con el sector seleccionado
![image](https://user-images.githubusercontent.com/13120924/34514527-20d78594-f06e-11e7-8396-8a33bb99284e.png)
TODO: incluir info de endpoint

**Comment by alasarr** [comment]
Por ahora nos olvidamos de la perdida de suministro.

**Comment by ignaciodomingo** [comment]
Endpoint:
`GET /aljarafe/entities/aq_cons.sector/elements?variables=aq_cons.sector.leak_status,aq_cons.sector.leak_rule,aq_cons.sector.flow,aq_cons.sector.pressure ´

**Comment by Josmorsot** [comment]
* [ ] Adaptar Widget de alerta para elegir entre 'Simple' o 'Detallado'
* [ ] Detallado: añadir descripción del problema y botón (sin funcionalidad) a orden de trabajo
