### ISSUE TITLE
Widget de peligro de fuga (gráfica de líneas y background)

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#79]
Este widget es para el modo con el sector seleccionado
![image](https://user-images.githubusercontent.com/13120924/34515191-37486110-f071-11e7-98e0-0bfe482127c6.png)

TODO: Añadir endpoint

**Comment by alasarr** [comment]
Hay que crear una variable para la columna status de "leak_historic".

**Comment by ignaciodomingo** [comment]
`POST /aljarafe/variables/timeserie`
```
{
  "agg": ["AVG","AVG","MIN"],
  "vars": ["aq_cons.sector.flow","aq_cons.sector.pressure","aq_cons.sector.leak_status"],
  "time": {
    "start": "2018-01-29T00:00:00Z",
    "finish": "2018-01-29T23:59:59Z",
    "step": "1h"
  },
  "filters": {
  	"id_entity__eq":"sector_id:19"
  }
}
```

**Comment by josemazo** [comment]
@ignaciodomingo funciona perfectamente ese endpoint, pero hay tener cuidao de pedir fechas en le existan datos. Cuando corra los históricos no habrá problemas. Otra cosa, del leak status hay que pedir el máximo, no el mínimo: 0 es flama, 1 es anomalía y 2 es fuga.

**Comment by ignaciodomingo** [comment]
cambiado mi comentario!

**Comment by Josmorsot** [comment]
* [ ] Dos ejes 'Y' (presión y caudal)
* [ ] fondo rojo a partir de detección

**Comment by ignaciodomingo** [comment]
UNRELATED
- [ ] Cambiar la llamada que se utiliza en evolución para sacar los nombres de los sectores: GET /aljarafe/entities/aq_cons.sector/elements
- [ ] Cambiar llamada para pedir plot en fugas para que se pida el now y quitando lo no necesario del body
