### ISSUE TITLE
Widget de comparativa

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#80]
![image](https://user-images.githubusercontent.com/13120924/34515213-4f406376-f071-11e7-8b65-ed2d0e5879a3.png)

Atención que este widget permite selecionar variable a comparar del sector: Presión y caudal

TODO: Añadir endpoint

**Comment by alasarr** [comment]
Confirmar con @neokore la estimación. No sé hasta que punto soporta esto el módulo de gráficos.

**Comment by neokore** [comment]
El selector de variable creo que existe en medio ambiente, aunque sí que veo dos elementos nuevos en esta gráfica, los dos estilos distintos de línea y lo que creo que es una media (la línea roja, podemos confirmar ese elemento?). Por ahora lo marcaría en 8 horas.
