### ISSUE TITLE
Widget de estado actual de fuga

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#81]
Este widget es para el modo con el sector seleccionado
![image](https://user-images.githubusercontent.com/13120924/34515265-94d6067a-f071-11e7-8912-ee592c62c1f1.png)
TODO: Añadir endpoints

QUitamos los porcentajes de subida o bajada.
  
Vamos a desarrollar un widget genérico para esto: un widget de N variables.

**Comment by IgnacioDomingo** [comment]
Los datos de este creo que se podrían sacar del GeoJSON directamente, si no:
`GET /aljarafe/devices/aq_cons.sector/sector_id:19/lastdata`

**Comment by Josmorsot** [comment]
* [ ] Debe aceptar un objeto con: 
- Título de variable
- Color de variable
- Unidad
- NumberFormat

* Aceptar título por param
