### ISSUE TITLE
Widget de caudal: últimas 24h

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#82]
Este widget es para el modo con el sector seleccionado
![image](https://user-images.githubusercontent.com/13120924/34515284-ad04e66c-f071-11e7-91d7-a1e6e8fa4eab.png)

TODO: Añadir endpoint

Se reutiliza el widget genérico. Añadimos la funcionalidad para añadir los iconos de max, min, avg. Se añaden solo si el widget tiene un parámetro activo, por ejemplo: showAggIcons.

**Comment by IgnacioDomingo** [comment]
`POST /aljarafe/variables/aq_cons.sector.flow/now`
```
{
	"agg":"AVG",
	"time":{
		"start":"2018-01-26T00:00:00Z",
		"finish":"2018-01-26T23:59:59Z"
		
	},
	"filters":{
		"condition":{
			"id_entity__eq":"sector_id:19"
		}
	}
}
```
agg hay que cambiarlo por max y min para obtenerlos todos los valores
