### ISSUE TITLE
Widget de presión: últimas 24h

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#83]
Este widget es para el modo con el sector seleccionado
![image](https://user-images.githubusercontent.com/13120924/34515307-d534bb4e-f071-11e7-91bf-e6341293f3e3.png)
TODO: Añadir endpoint
  
Utilizamos widget genérico con la variable de presión.

**Comment by IgnacioDomingo** [comment]
`POST /aljarafe/variables/aq_cons.sector.pressure/now`
```
{
	"agg":"AVG",
	"time":{
		"start":"2018-01-26T00:00:00Z",
		"finish":"2018-01-26T23:59:59Z"
		
	},
	"filters":{
		"condition":{
			"id_entity__eq":"sector_id:19"
		}
	}
}
```
agg hay que cambiarlo por max y min para obtenerlos todos los valores
