### ISSUE TITLE
Añadir metadatos de estado de depósito

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#90]
Necesitamos que la api devuelva información acerca del estado de los depósitos:
Datos actuales:
- Cantidad de agua en el depósito
- Estado: si hay anomalía o el estado es correcto
- Consumo eléctrico real
- Consumo eléctrico previsto
- Nivel minimo de llenado
- Nidel máximo de llenado

Datos históricos:
- Cantidad de agua en el depósito
- Estado: si hay anomalía o el estado es correcto
- Consumo eléctrico real
- Consumo eléctrico previsto
- Nivel minimo de llenado
- Nidel máximo de llenado

A esto hay que añadir que ya hay información estática para cada depósito en aq_cata.tank. Hay que ver cómo relacionarla O replicarla en los nuevos metadatos

Una nota respecto a los depósitos, en principio se ha asumido que cada depósito sólo alimenta un sector, por simplificar

También es necesario almacenar información acerca del plan de encendido previsto y el real, pero eso se hará en la tarea #125 

La pantalla es https://projects.invisionapp.com/d/main#/console/12071697/257069566/preview

**Comment by IgnacioDomingo** [comment]
@josemazo tenemos que ver que tenemos ya, en la api en /metadata no aparece nada de info de los depósitos, aunque sí como elemento estático en aq_cata.tank
