### ISSUE TITLE
Endpoint de plan de ahorro y anomalía de consumo

### ISSUE THREAD

**Issue by ignaciodomingo** [GeographicaGS/AquaGIS#91]
Tiene que atender a las dos versiones del widget:
![image](https://user-images.githubusercontent.com/13120924/34516571-a305f9d4-f077-11e7-9548-436a3666c1be.png)

![image](https://user-images.githubusercontent.com/13120924/34516587-ab47dc16-f077-11e7-8c30-240b172a229e.png)

Esto implica que hay que devolver información de los planes de consumo almacenados para cada día, tanto el plan real como el plan previsto

**Comment by ignaciodomingo** [comment]
@alejandrohall tenemos un problema con esto, deben estar tocando en su schema y ahora no hay manera de hacer funcionar el endpoint. Las tablas tendrían que estar en el schema de Urbo (aunque sean copiadas y pegadas).
Request:
`POST /aljarafe/aq_cons/tank/1/plans`
````
{
 "time": "2018-01-04"
}
````
Respuesta:
```
{
    "message": "relation \"phase2_v1.tank_pump\" does not exist",
    "error": {}
}
```

**Comment by alejandrohall** [comment]
Claro, ahora que acabo de caer es imposible que funcione, hay que copiarlo a urbo, pues esas tablas están fuera de la base de datos de urbo, están en la base de datos de __aquasig_energy__, yo las copié a mano en local, así que las copio en urbo.

**Comment by alejandrohall** [comment]
Ya están copiadas las tablas en urbo, los endpoints ya funcionan correctamente.

**Comment by ignaciodomingo** [comment]
Ya funciona
